package com.pluralsight.duckair.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * Airports definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class Airports implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for recordtypeindicator. */
    private String recordtypeindicator;

    /** Value for sitenumber. */
    private String sitenumber;

    /** Value for facilitytype. */
    private String facilitytype;

    /** Value for locationidentifier. */
    private String locationidentifier;

    /** Value for infoeffectivedate. */
    private Date infoeffectivedate;

    /** Value for faaregioncode. */
    private String faaregioncode;

    /** Value for faafieldofficecode. */
    private String faafieldofficecode;

    /** Value for stateabbr. */
    private String stateabbr;

    /** Value for statename. */
    private String statename;

    /** Value for county. */
    private String county;

    /** Value for countystatename. */
    private String countystatename;

    /** Value for city. */
    private String city;

    /** Value for facilityname. */
    private String facilityname;

    /** Value for ownershiptype. */
    private String ownershiptype;

    /** Value for facilityuse. */
    private String facilityuse;

    /** Value for ownername. */
    private String ownername;

    /** Value for owneraddress. */
    private String owneraddress;

    /** Value for ownercitystatezip. */
    private String ownercitystatezip;

    /** Value for ownerphone. */
    private String ownerphone;

    /** Value for managername. */
    private String managername;

    /** Value for manageraddress. */
    private String manageraddress;

    /** Value for managercitystatezip. */
    private String managercitystatezip;

    /** Value for managerphone. */
    private String managerphone;

    /** Value for referencepointlatitudef. */
    private String referencepointlatitudef;

    /** Value for referencepointlatitudes. */
    private String referencepointlatitudes;

    /** Value for referencepointlongitudef. */
    private String referencepointlongitudef;

    /** Value for referencepointlongitudes. */
    private String referencepointlongitudes;

    /** Value for referencepointmethod. */
    private String referencepointmethod;

    /** Value for airportelevation. */
    private BigDecimal airportelevation;

    /** Value for airportelevationmethod. */
    private String airportelevationmethod;

    /** Value for magneticvariation. */
    private String magneticvariation;

    /** Value for magneticvariationepoch. */
    private String magneticvariationepoch;

    /** Value for trafficpatternaltitude. */
    private Integer trafficpatternaltitude;

    /** Value for sectionalname. */
    private String sectionalname;

    /** Value for distancefromcity. */
    private String distancefromcity;

    /** Value for directiontocity. */
    private String directiontocity;

    /** Value for citydistrict. */
    private String citydistrict;

    /** Value for airportacres. */
    private String airportacres;

    /** Value for artccidentifier. */
    private String artccidentifier;

    /** Value for artcccomputeridentifier. */
    private String artcccomputeridentifier;

    /** Value for artccname. */
    private String artccname;

    /** Value for responsibleartccidentifier. */
    private String responsibleartccidentifier;

    /** Value for responsibleartccname. */
    private String responsibleartccname;

    /** Value for tieinfssonfield. */
    private String tieinfssonfield;

    /** Value for tieinfssidentifier. */
    private String tieinfssidentifier;

    /** Value for tieinfssname. */
    private String tieinfssname;

    /** Value for fssphonenumber. */
    private String fssphonenumber;

    /** Value for fsstollfreephone. */
    private String fsstollfreephone;

    /** Value for alternatefssidentifier. */
    private String alternatefssidentifier;

    /** Value for alternatefssname. */
    private String alternatefssname;

    /** Value for alternatefsstollfree. */
    private String alternatefsstollfree;

    /** Value for notamfacilityidentifier. */
    private String notamfacilityidentifier;

    /** Value for notamdavailable. */
    private String notamdavailable;

    /** Value for airportactivationdate. */
    private Date airportactivationdate;

    /** Value for airportstatuscode. */
    private String airportstatuscode;

    /** Value for airportarffcert. */
    private String airportarffcert;

    /** Value for agreementcode. */
    private String agreementcode;

    /** Value for airspaceanalysis. */
    private String airspaceanalysis;

    /** Value for international. */
    private String international;

    /** Value for offfieldcustoms. */
    private String offfieldcustoms;

    /** Value for militaryjointuse. */
    private String militaryjointuse;

    /** Value for militarylandingrights. */
    private String militarylandingrights;

    /** Value for inspectionmethod. */
    private String inspectionmethod;

    /** Value for inspectionagency. */
    private String inspectionagency;

    /** Value for lastinspection. */
    private Date lastinspection;

    /** Value for lastinformationrequest. */
    private Date lastinformationrequest;

    /** Value for fueltypes. */
    private String fueltypes;

    /** Value for airframerepair. */
    private String airframerepair;

    /** Value for powerplantrepair. */
    private String powerplantrepair;

    /** Value for bottledoxygen. */
    private String bottledoxygen;

    /** Value for bulkoxygen. */
    private String bulkoxygen;

    /** Value for lightingschedule. */
    private String lightingschedule;

    /** Value for beaconlightingschedule. */
    private String beaconlightingschedule;

    /** Value for toweronfield. */
    private String toweronfield;

    /** Value for unicomfrequency. */
    private String unicomfrequency;

    /** Value for ctafrequency. */
    private String ctafrequency;

    /** Value for segmentedcircle. */
    private String segmentedcircle;

    /** Value for beaconcolor. */
    private String beaconcolor;

    /** Value for landingfee. */
    private String landingfee;

    /** Value for medicaluse. */
    private String medicaluse;

    /** Value for singleengine. */
    private String singleengine;

    /** Value for multiengine. */
    private String multiengine;

    /** Value for jetengine. */
    private String jetengine;

    /** Value for helicopter. */
    private String helicopter;

    /** Value for gliders. */
    private String gliders;

    /** Value for military. */
    private String military;

    /** Value for ultralight. */
    private String ultralight;

    /** Value for commercialservices. */
    private String commercialservices;

    /** Value for commuterservices. */
    private String commuterservices;

    /** Value for airtaxiservices. */
    private String airtaxiservices;

    /** Value for generalaviationlocal. */
    private String generalaviationlocal;

    /** Value for generalaviationitinerant. */
    private String generalaviationitinerant;

    /** Value for militaryoperations. */
    private String militaryoperations;

    /** Value for operationsdataexpires. */
    private Date operationsdataexpires;

    /** Value for positionsource. */
    private String positionsource;

    /** Value for positionsourcedate. */
    private Timestamp positionsourcedate;

    /** Value for elevationsource. */
    private String elevationsource;

    /** Value for elevationsourcedate. */
    private Timestamp elevationsourcedate;

    /** Value for contractfuel. */
    private String contractfuel;

    /** Value for transientstorage. */
    private String transientstorage;

    /** Value for otherservices. */
    private String otherservices;

    /** Value for windsock. */
    private String windsock;

    /** Value for icao. */
    private String icao;

    /** Value for latitude. */
    private BigDecimal latitude;

    /** Value for longitude. */
    private BigDecimal longitude;

    /** Value for isserviced. */
    private Boolean isserviced;

    /** Empty constructor. **/
    public Airports() {
        // No-op.
    }

    /** Full constructor. **/
    public Airports(String recordtypeindicator,
        String sitenumber,
        String facilitytype,
        String locationidentifier,
        Date infoeffectivedate,
        String faaregioncode,
        String faafieldofficecode,
        String stateabbr,
        String statename,
        String county,
        String countystatename,
        String city,
        String facilityname,
        String ownershiptype,
        String facilityuse,
        String ownername,
        String owneraddress,
        String ownercitystatezip,
        String ownerphone,
        String managername,
        String manageraddress,
        String managercitystatezip,
        String managerphone,
        String referencepointlatitudef,
        String referencepointlatitudes,
        String referencepointlongitudef,
        String referencepointlongitudes,
        String referencepointmethod,
        BigDecimal airportelevation,
        String airportelevationmethod,
        String magneticvariation,
        String magneticvariationepoch,
        Integer trafficpatternaltitude,
        String sectionalname,
        String distancefromcity,
        String directiontocity,
        String citydistrict,
        String airportacres,
        String artccidentifier,
        String artcccomputeridentifier,
        String artccname,
        String responsibleartccidentifier,
        String responsibleartccname,
        String tieinfssonfield,
        String tieinfssidentifier,
        String tieinfssname,
        String fssphonenumber,
        String fsstollfreephone,
        String alternatefssidentifier,
        String alternatefssname,
        String alternatefsstollfree,
        String notamfacilityidentifier,
        String notamdavailable,
        Date airportactivationdate,
        String airportstatuscode,
        String airportarffcert,
        String agreementcode,
        String airspaceanalysis,
        String international,
        String offfieldcustoms,
        String militaryjointuse,
        String militarylandingrights,
        String inspectionmethod,
        String inspectionagency,
        Date lastinspection,
        Date lastinformationrequest,
        String fueltypes,
        String airframerepair,
        String powerplantrepair,
        String bottledoxygen,
        String bulkoxygen,
        String lightingschedule,
        String beaconlightingschedule,
        String toweronfield,
        String unicomfrequency,
        String ctafrequency,
        String segmentedcircle,
        String beaconcolor,
        String landingfee,
        String medicaluse,
        String singleengine,
        String multiengine,
        String jetengine,
        String helicopter,
        String gliders,
        String military,
        String ultralight,
        String commercialservices,
        String commuterservices,
        String airtaxiservices,
        String generalaviationlocal,
        String generalaviationitinerant,
        String militaryoperations,
        Date operationsdataexpires,
        String positionsource,
        Timestamp positionsourcedate,
        String elevationsource,
        Timestamp elevationsourcedate,
        String contractfuel,
        String transientstorage,
        String otherservices,
        String windsock,
        String icao,
        BigDecimal latitude,
        BigDecimal longitude,
        Boolean isserviced) {
        this.recordtypeindicator = recordtypeindicator;
        this.sitenumber = sitenumber;
        this.facilitytype = facilitytype;
        this.locationidentifier = locationidentifier;
        this.infoeffectivedate = infoeffectivedate;
        this.faaregioncode = faaregioncode;
        this.faafieldofficecode = faafieldofficecode;
        this.stateabbr = stateabbr;
        this.statename = statename;
        this.county = county;
        this.countystatename = countystatename;
        this.city = city;
        this.facilityname = facilityname;
        this.ownershiptype = ownershiptype;
        this.facilityuse = facilityuse;
        this.ownername = ownername;
        this.owneraddress = owneraddress;
        this.ownercitystatezip = ownercitystatezip;
        this.ownerphone = ownerphone;
        this.managername = managername;
        this.manageraddress = manageraddress;
        this.managercitystatezip = managercitystatezip;
        this.managerphone = managerphone;
        this.referencepointlatitudef = referencepointlatitudef;
        this.referencepointlatitudes = referencepointlatitudes;
        this.referencepointlongitudef = referencepointlongitudef;
        this.referencepointlongitudes = referencepointlongitudes;
        this.referencepointmethod = referencepointmethod;
        this.airportelevation = airportelevation;
        this.airportelevationmethod = airportelevationmethod;
        this.magneticvariation = magneticvariation;
        this.magneticvariationepoch = magneticvariationepoch;
        this.trafficpatternaltitude = trafficpatternaltitude;
        this.sectionalname = sectionalname;
        this.distancefromcity = distancefromcity;
        this.directiontocity = directiontocity;
        this.citydistrict = citydistrict;
        this.airportacres = airportacres;
        this.artccidentifier = artccidentifier;
        this.artcccomputeridentifier = artcccomputeridentifier;
        this.artccname = artccname;
        this.responsibleartccidentifier = responsibleartccidentifier;
        this.responsibleartccname = responsibleartccname;
        this.tieinfssonfield = tieinfssonfield;
        this.tieinfssidentifier = tieinfssidentifier;
        this.tieinfssname = tieinfssname;
        this.fssphonenumber = fssphonenumber;
        this.fsstollfreephone = fsstollfreephone;
        this.alternatefssidentifier = alternatefssidentifier;
        this.alternatefssname = alternatefssname;
        this.alternatefsstollfree = alternatefsstollfree;
        this.notamfacilityidentifier = notamfacilityidentifier;
        this.notamdavailable = notamdavailable;
        this.airportactivationdate = airportactivationdate;
        this.airportstatuscode = airportstatuscode;
        this.airportarffcert = airportarffcert;
        this.agreementcode = agreementcode;
        this.airspaceanalysis = airspaceanalysis;
        this.international = international;
        this.offfieldcustoms = offfieldcustoms;
        this.militaryjointuse = militaryjointuse;
        this.militarylandingrights = militarylandingrights;
        this.inspectionmethod = inspectionmethod;
        this.inspectionagency = inspectionagency;
        this.lastinspection = lastinspection;
        this.lastinformationrequest = lastinformationrequest;
        this.fueltypes = fueltypes;
        this.airframerepair = airframerepair;
        this.powerplantrepair = powerplantrepair;
        this.bottledoxygen = bottledoxygen;
        this.bulkoxygen = bulkoxygen;
        this.lightingschedule = lightingschedule;
        this.beaconlightingschedule = beaconlightingschedule;
        this.toweronfield = toweronfield;
        this.unicomfrequency = unicomfrequency;
        this.ctafrequency = ctafrequency;
        this.segmentedcircle = segmentedcircle;
        this.beaconcolor = beaconcolor;
        this.landingfee = landingfee;
        this.medicaluse = medicaluse;
        this.singleengine = singleengine;
        this.multiengine = multiengine;
        this.jetengine = jetengine;
        this.helicopter = helicopter;
        this.gliders = gliders;
        this.military = military;
        this.ultralight = ultralight;
        this.commercialservices = commercialservices;
        this.commuterservices = commuterservices;
        this.airtaxiservices = airtaxiservices;
        this.generalaviationlocal = generalaviationlocal;
        this.generalaviationitinerant = generalaviationitinerant;
        this.militaryoperations = militaryoperations;
        this.operationsdataexpires = operationsdataexpires;
        this.positionsource = positionsource;
        this.positionsourcedate = positionsourcedate;
        this.elevationsource = elevationsource;
        this.elevationsourcedate = elevationsourcedate;
        this.contractfuel = contractfuel;
        this.transientstorage = transientstorage;
        this.otherservices = otherservices;
        this.windsock = windsock;
        this.icao = icao;
        this.latitude = latitude;
        this.longitude = longitude;
        this.isserviced = isserviced;
    }

    /**
     * Gets recordtypeindicator
     * 
     * @return Value for recordtypeindicator.
     **/
    public String getRecordtypeindicator() {
        return recordtypeindicator;
    }

    /**
     * Sets recordtypeindicator
     * 
     * @param recordtypeindicator New value for recordtypeindicator.
     **/
    public void setRecordtypeindicator(String recordtypeindicator) {
        this.recordtypeindicator = recordtypeindicator;
    }

    /**
     * Gets sitenumber
     * 
     * @return Value for sitenumber.
     **/
    public String getSitenumber() {
        return sitenumber;
    }

    /**
     * Sets sitenumber
     * 
     * @param sitenumber New value for sitenumber.
     **/
    public void setSitenumber(String sitenumber) {
        this.sitenumber = sitenumber;
    }

    /**
     * Gets facilitytype
     * 
     * @return Value for facilitytype.
     **/
    public String getFacilitytype() {
        return facilitytype;
    }

    /**
     * Sets facilitytype
     * 
     * @param facilitytype New value for facilitytype.
     **/
    public void setFacilitytype(String facilitytype) {
        this.facilitytype = facilitytype;
    }

    /**
     * Gets locationidentifier
     * 
     * @return Value for locationidentifier.
     **/
    public String getLocationidentifier() {
        return locationidentifier;
    }

    /**
     * Sets locationidentifier
     * 
     * @param locationidentifier New value for locationidentifier.
     **/
    public void setLocationidentifier(String locationidentifier) {
        this.locationidentifier = locationidentifier;
    }

    /**
     * Gets infoeffectivedate
     * 
     * @return Value for infoeffectivedate.
     **/
    public Date getInfoeffectivedate() {
        return infoeffectivedate;
    }

    /**
     * Sets infoeffectivedate
     * 
     * @param infoeffectivedate New value for infoeffectivedate.
     **/
    public void setInfoeffectivedate(Date infoeffectivedate) {
        this.infoeffectivedate = infoeffectivedate;
    }

    /**
     * Gets faaregioncode
     * 
     * @return Value for faaregioncode.
     **/
    public String getFaaregioncode() {
        return faaregioncode;
    }

    /**
     * Sets faaregioncode
     * 
     * @param faaregioncode New value for faaregioncode.
     **/
    public void setFaaregioncode(String faaregioncode) {
        this.faaregioncode = faaregioncode;
    }

    /**
     * Gets faafieldofficecode
     * 
     * @return Value for faafieldofficecode.
     **/
    public String getFaafieldofficecode() {
        return faafieldofficecode;
    }

    /**
     * Sets faafieldofficecode
     * 
     * @param faafieldofficecode New value for faafieldofficecode.
     **/
    public void setFaafieldofficecode(String faafieldofficecode) {
        this.faafieldofficecode = faafieldofficecode;
    }

    /**
     * Gets stateabbr
     * 
     * @return Value for stateabbr.
     **/
    public String getStateabbr() {
        return stateabbr;
    }

    /**
     * Sets stateabbr
     * 
     * @param stateabbr New value for stateabbr.
     **/
    public void setStateabbr(String stateabbr) {
        this.stateabbr = stateabbr;
    }

    /**
     * Gets statename
     * 
     * @return Value for statename.
     **/
    public String getStatename() {
        return statename;
    }

    /**
     * Sets statename
     * 
     * @param statename New value for statename.
     **/
    public void setStatename(String statename) {
        this.statename = statename;
    }

    /**
     * Gets county
     * 
     * @return Value for county.
     **/
    public String getCounty() {
        return county;
    }

    /**
     * Sets county
     * 
     * @param county New value for county.
     **/
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * Gets countystatename
     * 
     * @return Value for countystatename.
     **/
    public String getCountystatename() {
        return countystatename;
    }

    /**
     * Sets countystatename
     * 
     * @param countystatename New value for countystatename.
     **/
    public void setCountystatename(String countystatename) {
        this.countystatename = countystatename;
    }

    /**
     * Gets city
     * 
     * @return Value for city.
     **/
    public String getCity() {
        return city;
    }

    /**
     * Sets city
     * 
     * @param city New value for city.
     **/
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Gets facilityname
     * 
     * @return Value for facilityname.
     **/
    public String getFacilityname() {
        return facilityname;
    }

    /**
     * Sets facilityname
     * 
     * @param facilityname New value for facilityname.
     **/
    public void setFacilityname(String facilityname) {
        this.facilityname = facilityname;
    }

    /**
     * Gets ownershiptype
     * 
     * @return Value for ownershiptype.
     **/
    public String getOwnershiptype() {
        return ownershiptype;
    }

    /**
     * Sets ownershiptype
     * 
     * @param ownershiptype New value for ownershiptype.
     **/
    public void setOwnershiptype(String ownershiptype) {
        this.ownershiptype = ownershiptype;
    }

    /**
     * Gets facilityuse
     * 
     * @return Value for facilityuse.
     **/
    public String getFacilityuse() {
        return facilityuse;
    }

    /**
     * Sets facilityuse
     * 
     * @param facilityuse New value for facilityuse.
     **/
    public void setFacilityuse(String facilityuse) {
        this.facilityuse = facilityuse;
    }

    /**
     * Gets ownername
     * 
     * @return Value for ownername.
     **/
    public String getOwnername() {
        return ownername;
    }

    /**
     * Sets ownername
     * 
     * @param ownername New value for ownername.
     **/
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }

    /**
     * Gets owneraddress
     * 
     * @return Value for owneraddress.
     **/
    public String getOwneraddress() {
        return owneraddress;
    }

    /**
     * Sets owneraddress
     * 
     * @param owneraddress New value for owneraddress.
     **/
    public void setOwneraddress(String owneraddress) {
        this.owneraddress = owneraddress;
    }

    /**
     * Gets ownercitystatezip
     * 
     * @return Value for ownercitystatezip.
     **/
    public String getOwnercitystatezip() {
        return ownercitystatezip;
    }

    /**
     * Sets ownercitystatezip
     * 
     * @param ownercitystatezip New value for ownercitystatezip.
     **/
    public void setOwnercitystatezip(String ownercitystatezip) {
        this.ownercitystatezip = ownercitystatezip;
    }

    /**
     * Gets ownerphone
     * 
     * @return Value for ownerphone.
     **/
    public String getOwnerphone() {
        return ownerphone;
    }

    /**
     * Sets ownerphone
     * 
     * @param ownerphone New value for ownerphone.
     **/
    public void setOwnerphone(String ownerphone) {
        this.ownerphone = ownerphone;
    }

    /**
     * Gets managername
     * 
     * @return Value for managername.
     **/
    public String getManagername() {
        return managername;
    }

    /**
     * Sets managername
     * 
     * @param managername New value for managername.
     **/
    public void setManagername(String managername) {
        this.managername = managername;
    }

    /**
     * Gets manageraddress
     * 
     * @return Value for manageraddress.
     **/
    public String getManageraddress() {
        return manageraddress;
    }

    /**
     * Sets manageraddress
     * 
     * @param manageraddress New value for manageraddress.
     **/
    public void setManageraddress(String manageraddress) {
        this.manageraddress = manageraddress;
    }

    /**
     * Gets managercitystatezip
     * 
     * @return Value for managercitystatezip.
     **/
    public String getManagercitystatezip() {
        return managercitystatezip;
    }

    /**
     * Sets managercitystatezip
     * 
     * @param managercitystatezip New value for managercitystatezip.
     **/
    public void setManagercitystatezip(String managercitystatezip) {
        this.managercitystatezip = managercitystatezip;
    }

    /**
     * Gets managerphone
     * 
     * @return Value for managerphone.
     **/
    public String getManagerphone() {
        return managerphone;
    }

    /**
     * Sets managerphone
     * 
     * @param managerphone New value for managerphone.
     **/
    public void setManagerphone(String managerphone) {
        this.managerphone = managerphone;
    }

    /**
     * Gets referencepointlatitudef
     * 
     * @return Value for referencepointlatitudef.
     **/
    public String getReferencepointlatitudef() {
        return referencepointlatitudef;
    }

    /**
     * Sets referencepointlatitudef
     * 
     * @param referencepointlatitudef New value for referencepointlatitudef.
     **/
    public void setReferencepointlatitudef(String referencepointlatitudef) {
        this.referencepointlatitudef = referencepointlatitudef;
    }

    /**
     * Gets referencepointlatitudes
     * 
     * @return Value for referencepointlatitudes.
     **/
    public String getReferencepointlatitudes() {
        return referencepointlatitudes;
    }

    /**
     * Sets referencepointlatitudes
     * 
     * @param referencepointlatitudes New value for referencepointlatitudes.
     **/
    public void setReferencepointlatitudes(String referencepointlatitudes) {
        this.referencepointlatitudes = referencepointlatitudes;
    }

    /**
     * Gets referencepointlongitudef
     * 
     * @return Value for referencepointlongitudef.
     **/
    public String getReferencepointlongitudef() {
        return referencepointlongitudef;
    }

    /**
     * Sets referencepointlongitudef
     * 
     * @param referencepointlongitudef New value for referencepointlongitudef.
     **/
    public void setReferencepointlongitudef(String referencepointlongitudef) {
        this.referencepointlongitudef = referencepointlongitudef;
    }

    /**
     * Gets referencepointlongitudes
     * 
     * @return Value for referencepointlongitudes.
     **/
    public String getReferencepointlongitudes() {
        return referencepointlongitudes;
    }

    /**
     * Sets referencepointlongitudes
     * 
     * @param referencepointlongitudes New value for referencepointlongitudes.
     **/
    public void setReferencepointlongitudes(String referencepointlongitudes) {
        this.referencepointlongitudes = referencepointlongitudes;
    }

    /**
     * Gets referencepointmethod
     * 
     * @return Value for referencepointmethod.
     **/
    public String getReferencepointmethod() {
        return referencepointmethod;
    }

    /**
     * Sets referencepointmethod
     * 
     * @param referencepointmethod New value for referencepointmethod.
     **/
    public void setReferencepointmethod(String referencepointmethod) {
        this.referencepointmethod = referencepointmethod;
    }

    /**
     * Gets airportelevation
     * 
     * @return Value for airportelevation.
     **/
    public BigDecimal getAirportelevation() {
        return airportelevation;
    }

    /**
     * Sets airportelevation
     * 
     * @param airportelevation New value for airportelevation.
     **/
    public void setAirportelevation(BigDecimal airportelevation) {
        this.airportelevation = airportelevation;
    }

    /**
     * Gets airportelevationmethod
     * 
     * @return Value for airportelevationmethod.
     **/
    public String getAirportelevationmethod() {
        return airportelevationmethod;
    }

    /**
     * Sets airportelevationmethod
     * 
     * @param airportelevationmethod New value for airportelevationmethod.
     **/
    public void setAirportelevationmethod(String airportelevationmethod) {
        this.airportelevationmethod = airportelevationmethod;
    }

    /**
     * Gets magneticvariation
     * 
     * @return Value for magneticvariation.
     **/
    public String getMagneticvariation() {
        return magneticvariation;
    }

    /**
     * Sets magneticvariation
     * 
     * @param magneticvariation New value for magneticvariation.
     **/
    public void setMagneticvariation(String magneticvariation) {
        this.magneticvariation = magneticvariation;
    }

    /**
     * Gets magneticvariationepoch
     * 
     * @return Value for magneticvariationepoch.
     **/
    public String getMagneticvariationepoch() {
        return magneticvariationepoch;
    }

    /**
     * Sets magneticvariationepoch
     * 
     * @param magneticvariationepoch New value for magneticvariationepoch.
     **/
    public void setMagneticvariationepoch(String magneticvariationepoch) {
        this.magneticvariationepoch = magneticvariationepoch;
    }

    /**
     * Gets trafficpatternaltitude
     * 
     * @return Value for trafficpatternaltitude.
     **/
    public Integer getTrafficpatternaltitude() {
        return trafficpatternaltitude;
    }

    /**
     * Sets trafficpatternaltitude
     * 
     * @param trafficpatternaltitude New value for trafficpatternaltitude.
     **/
    public void setTrafficpatternaltitude(Integer trafficpatternaltitude) {
        this.trafficpatternaltitude = trafficpatternaltitude;
    }

    /**
     * Gets sectionalname
     * 
     * @return Value for sectionalname.
     **/
    public String getSectionalname() {
        return sectionalname;
    }

    /**
     * Sets sectionalname
     * 
     * @param sectionalname New value for sectionalname.
     **/
    public void setSectionalname(String sectionalname) {
        this.sectionalname = sectionalname;
    }

    /**
     * Gets distancefromcity
     * 
     * @return Value for distancefromcity.
     **/
    public String getDistancefromcity() {
        return distancefromcity;
    }

    /**
     * Sets distancefromcity
     * 
     * @param distancefromcity New value for distancefromcity.
     **/
    public void setDistancefromcity(String distancefromcity) {
        this.distancefromcity = distancefromcity;
    }

    /**
     * Gets directiontocity
     * 
     * @return Value for directiontocity.
     **/
    public String getDirectiontocity() {
        return directiontocity;
    }

    /**
     * Sets directiontocity
     * 
     * @param directiontocity New value for directiontocity.
     **/
    public void setDirectiontocity(String directiontocity) {
        this.directiontocity = directiontocity;
    }

    /**
     * Gets citydistrict
     * 
     * @return Value for citydistrict.
     **/
    public String getCitydistrict() {
        return citydistrict;
    }

    /**
     * Sets citydistrict
     * 
     * @param citydistrict New value for citydistrict.
     **/
    public void setCitydistrict(String citydistrict) {
        this.citydistrict = citydistrict;
    }

    /**
     * Gets airportacres
     * 
     * @return Value for airportacres.
     **/
    public String getAirportacres() {
        return airportacres;
    }

    /**
     * Sets airportacres
     * 
     * @param airportacres New value for airportacres.
     **/
    public void setAirportacres(String airportacres) {
        this.airportacres = airportacres;
    }

    /**
     * Gets artccidentifier
     * 
     * @return Value for artccidentifier.
     **/
    public String getArtccidentifier() {
        return artccidentifier;
    }

    /**
     * Sets artccidentifier
     * 
     * @param artccidentifier New value for artccidentifier.
     **/
    public void setArtccidentifier(String artccidentifier) {
        this.artccidentifier = artccidentifier;
    }

    /**
     * Gets artcccomputeridentifier
     * 
     * @return Value for artcccomputeridentifier.
     **/
    public String getArtcccomputeridentifier() {
        return artcccomputeridentifier;
    }

    /**
     * Sets artcccomputeridentifier
     * 
     * @param artcccomputeridentifier New value for artcccomputeridentifier.
     **/
    public void setArtcccomputeridentifier(String artcccomputeridentifier) {
        this.artcccomputeridentifier = artcccomputeridentifier;
    }

    /**
     * Gets artccname
     * 
     * @return Value for artccname.
     **/
    public String getArtccname() {
        return artccname;
    }

    /**
     * Sets artccname
     * 
     * @param artccname New value for artccname.
     **/
    public void setArtccname(String artccname) {
        this.artccname = artccname;
    }

    /**
     * Gets responsibleartccidentifier
     * 
     * @return Value for responsibleartccidentifier.
     **/
    public String getResponsibleartccidentifier() {
        return responsibleartccidentifier;
    }

    /**
     * Sets responsibleartccidentifier
     * 
     * @param responsibleartccidentifier New value for responsibleartccidentifier.
     **/
    public void setResponsibleartccidentifier(String responsibleartccidentifier) {
        this.responsibleartccidentifier = responsibleartccidentifier;
    }

    /**
     * Gets responsibleartccname
     * 
     * @return Value for responsibleartccname.
     **/
    public String getResponsibleartccname() {
        return responsibleartccname;
    }

    /**
     * Sets responsibleartccname
     * 
     * @param responsibleartccname New value for responsibleartccname.
     **/
    public void setResponsibleartccname(String responsibleartccname) {
        this.responsibleartccname = responsibleartccname;
    }

    /**
     * Gets tieinfssonfield
     * 
     * @return Value for tieinfssonfield.
     **/
    public String getTieinfssonfield() {
        return tieinfssonfield;
    }

    /**
     * Sets tieinfssonfield
     * 
     * @param tieinfssonfield New value for tieinfssonfield.
     **/
    public void setTieinfssonfield(String tieinfssonfield) {
        this.tieinfssonfield = tieinfssonfield;
    }

    /**
     * Gets tieinfssidentifier
     * 
     * @return Value for tieinfssidentifier.
     **/
    public String getTieinfssidentifier() {
        return tieinfssidentifier;
    }

    /**
     * Sets tieinfssidentifier
     * 
     * @param tieinfssidentifier New value for tieinfssidentifier.
     **/
    public void setTieinfssidentifier(String tieinfssidentifier) {
        this.tieinfssidentifier = tieinfssidentifier;
    }

    /**
     * Gets tieinfssname
     * 
     * @return Value for tieinfssname.
     **/
    public String getTieinfssname() {
        return tieinfssname;
    }

    /**
     * Sets tieinfssname
     * 
     * @param tieinfssname New value for tieinfssname.
     **/
    public void setTieinfssname(String tieinfssname) {
        this.tieinfssname = tieinfssname;
    }

    /**
     * Gets fssphonenumber
     * 
     * @return Value for fssphonenumber.
     **/
    public String getFssphonenumber() {
        return fssphonenumber;
    }

    /**
     * Sets fssphonenumber
     * 
     * @param fssphonenumber New value for fssphonenumber.
     **/
    public void setFssphonenumber(String fssphonenumber) {
        this.fssphonenumber = fssphonenumber;
    }

    /**
     * Gets fsstollfreephone
     * 
     * @return Value for fsstollfreephone.
     **/
    public String getFsstollfreephone() {
        return fsstollfreephone;
    }

    /**
     * Sets fsstollfreephone
     * 
     * @param fsstollfreephone New value for fsstollfreephone.
     **/
    public void setFsstollfreephone(String fsstollfreephone) {
        this.fsstollfreephone = fsstollfreephone;
    }

    /**
     * Gets alternatefssidentifier
     * 
     * @return Value for alternatefssidentifier.
     **/
    public String getAlternatefssidentifier() {
        return alternatefssidentifier;
    }

    /**
     * Sets alternatefssidentifier
     * 
     * @param alternatefssidentifier New value for alternatefssidentifier.
     **/
    public void setAlternatefssidentifier(String alternatefssidentifier) {
        this.alternatefssidentifier = alternatefssidentifier;
    }

    /**
     * Gets alternatefssname
     * 
     * @return Value for alternatefssname.
     **/
    public String getAlternatefssname() {
        return alternatefssname;
    }

    /**
     * Sets alternatefssname
     * 
     * @param alternatefssname New value for alternatefssname.
     **/
    public void setAlternatefssname(String alternatefssname) {
        this.alternatefssname = alternatefssname;
    }

    /**
     * Gets alternatefsstollfree
     * 
     * @return Value for alternatefsstollfree.
     **/
    public String getAlternatefsstollfree() {
        return alternatefsstollfree;
    }

    /**
     * Sets alternatefsstollfree
     * 
     * @param alternatefsstollfree New value for alternatefsstollfree.
     **/
    public void setAlternatefsstollfree(String alternatefsstollfree) {
        this.alternatefsstollfree = alternatefsstollfree;
    }

    /**
     * Gets notamfacilityidentifier
     * 
     * @return Value for notamfacilityidentifier.
     **/
    public String getNotamfacilityidentifier() {
        return notamfacilityidentifier;
    }

    /**
     * Sets notamfacilityidentifier
     * 
     * @param notamfacilityidentifier New value for notamfacilityidentifier.
     **/
    public void setNotamfacilityidentifier(String notamfacilityidentifier) {
        this.notamfacilityidentifier = notamfacilityidentifier;
    }

    /**
     * Gets notamdavailable
     * 
     * @return Value for notamdavailable.
     **/
    public String getNotamdavailable() {
        return notamdavailable;
    }

    /**
     * Sets notamdavailable
     * 
     * @param notamdavailable New value for notamdavailable.
     **/
    public void setNotamdavailable(String notamdavailable) {
        this.notamdavailable = notamdavailable;
    }

    /**
     * Gets airportactivationdate
     * 
     * @return Value for airportactivationdate.
     **/
    public Date getAirportactivationdate() {
        return airportactivationdate;
    }

    /**
     * Sets airportactivationdate
     * 
     * @param airportactivationdate New value for airportactivationdate.
     **/
    public void setAirportactivationdate(Date airportactivationdate) {
        this.airportactivationdate = airportactivationdate;
    }

    /**
     * Gets airportstatuscode
     * 
     * @return Value for airportstatuscode.
     **/
    public String getAirportstatuscode() {
        return airportstatuscode;
    }

    /**
     * Sets airportstatuscode
     * 
     * @param airportstatuscode New value for airportstatuscode.
     **/
    public void setAirportstatuscode(String airportstatuscode) {
        this.airportstatuscode = airportstatuscode;
    }

    /**
     * Gets airportarffcert
     * 
     * @return Value for airportarffcert.
     **/
    public String getAirportarffcert() {
        return airportarffcert;
    }

    /**
     * Sets airportarffcert
     * 
     * @param airportarffcert New value for airportarffcert.
     **/
    public void setAirportarffcert(String airportarffcert) {
        this.airportarffcert = airportarffcert;
    }

    /**
     * Gets agreementcode
     * 
     * @return Value for agreementcode.
     **/
    public String getAgreementcode() {
        return agreementcode;
    }

    /**
     * Sets agreementcode
     * 
     * @param agreementcode New value for agreementcode.
     **/
    public void setAgreementcode(String agreementcode) {
        this.agreementcode = agreementcode;
    }

    /**
     * Gets airspaceanalysis
     * 
     * @return Value for airspaceanalysis.
     **/
    public String getAirspaceanalysis() {
        return airspaceanalysis;
    }

    /**
     * Sets airspaceanalysis
     * 
     * @param airspaceanalysis New value for airspaceanalysis.
     **/
    public void setAirspaceanalysis(String airspaceanalysis) {
        this.airspaceanalysis = airspaceanalysis;
    }

    /**
     * Gets international
     * 
     * @return Value for international.
     **/
    public String getInternational() {
        return international;
    }

    /**
     * Sets international
     * 
     * @param international New value for international.
     **/
    public void setInternational(String international) {
        this.international = international;
    }

    /**
     * Gets offfieldcustoms
     * 
     * @return Value for offfieldcustoms.
     **/
    public String getOfffieldcustoms() {
        return offfieldcustoms;
    }

    /**
     * Sets offfieldcustoms
     * 
     * @param offfieldcustoms New value for offfieldcustoms.
     **/
    public void setOfffieldcustoms(String offfieldcustoms) {
        this.offfieldcustoms = offfieldcustoms;
    }

    /**
     * Gets militaryjointuse
     * 
     * @return Value for militaryjointuse.
     **/
    public String getMilitaryjointuse() {
        return militaryjointuse;
    }

    /**
     * Sets militaryjointuse
     * 
     * @param militaryjointuse New value for militaryjointuse.
     **/
    public void setMilitaryjointuse(String militaryjointuse) {
        this.militaryjointuse = militaryjointuse;
    }

    /**
     * Gets militarylandingrights
     * 
     * @return Value for militarylandingrights.
     **/
    public String getMilitarylandingrights() {
        return militarylandingrights;
    }

    /**
     * Sets militarylandingrights
     * 
     * @param militarylandingrights New value for militarylandingrights.
     **/
    public void setMilitarylandingrights(String militarylandingrights) {
        this.militarylandingrights = militarylandingrights;
    }

    /**
     * Gets inspectionmethod
     * 
     * @return Value for inspectionmethod.
     **/
    public String getInspectionmethod() {
        return inspectionmethod;
    }

    /**
     * Sets inspectionmethod
     * 
     * @param inspectionmethod New value for inspectionmethod.
     **/
    public void setInspectionmethod(String inspectionmethod) {
        this.inspectionmethod = inspectionmethod;
    }

    /**
     * Gets inspectionagency
     * 
     * @return Value for inspectionagency.
     **/
    public String getInspectionagency() {
        return inspectionagency;
    }

    /**
     * Sets inspectionagency
     * 
     * @param inspectionagency New value for inspectionagency.
     **/
    public void setInspectionagency(String inspectionagency) {
        this.inspectionagency = inspectionagency;
    }

    /**
     * Gets lastinspection
     * 
     * @return Value for lastinspection.
     **/
    public Date getLastinspection() {
        return lastinspection;
    }

    /**
     * Sets lastinspection
     * 
     * @param lastinspection New value for lastinspection.
     **/
    public void setLastinspection(Date lastinspection) {
        this.lastinspection = lastinspection;
    }

    /**
     * Gets lastinformationrequest
     * 
     * @return Value for lastinformationrequest.
     **/
    public Date getLastinformationrequest() {
        return lastinformationrequest;
    }

    /**
     * Sets lastinformationrequest
     * 
     * @param lastinformationrequest New value for lastinformationrequest.
     **/
    public void setLastinformationrequest(Date lastinformationrequest) {
        this.lastinformationrequest = lastinformationrequest;
    }

    /**
     * Gets fueltypes
     * 
     * @return Value for fueltypes.
     **/
    public String getFueltypes() {
        return fueltypes;
    }

    /**
     * Sets fueltypes
     * 
     * @param fueltypes New value for fueltypes.
     **/
    public void setFueltypes(String fueltypes) {
        this.fueltypes = fueltypes;
    }

    /**
     * Gets airframerepair
     * 
     * @return Value for airframerepair.
     **/
    public String getAirframerepair() {
        return airframerepair;
    }

    /**
     * Sets airframerepair
     * 
     * @param airframerepair New value for airframerepair.
     **/
    public void setAirframerepair(String airframerepair) {
        this.airframerepair = airframerepair;
    }

    /**
     * Gets powerplantrepair
     * 
     * @return Value for powerplantrepair.
     **/
    public String getPowerplantrepair() {
        return powerplantrepair;
    }

    /**
     * Sets powerplantrepair
     * 
     * @param powerplantrepair New value for powerplantrepair.
     **/
    public void setPowerplantrepair(String powerplantrepair) {
        this.powerplantrepair = powerplantrepair;
    }

    /**
     * Gets bottledoxygen
     * 
     * @return Value for bottledoxygen.
     **/
    public String getBottledoxygen() {
        return bottledoxygen;
    }

    /**
     * Sets bottledoxygen
     * 
     * @param bottledoxygen New value for bottledoxygen.
     **/
    public void setBottledoxygen(String bottledoxygen) {
        this.bottledoxygen = bottledoxygen;
    }

    /**
     * Gets bulkoxygen
     * 
     * @return Value for bulkoxygen.
     **/
    public String getBulkoxygen() {
        return bulkoxygen;
    }

    /**
     * Sets bulkoxygen
     * 
     * @param bulkoxygen New value for bulkoxygen.
     **/
    public void setBulkoxygen(String bulkoxygen) {
        this.bulkoxygen = bulkoxygen;
    }

    /**
     * Gets lightingschedule
     * 
     * @return Value for lightingschedule.
     **/
    public String getLightingschedule() {
        return lightingschedule;
    }

    /**
     * Sets lightingschedule
     * 
     * @param lightingschedule New value for lightingschedule.
     **/
    public void setLightingschedule(String lightingschedule) {
        this.lightingschedule = lightingschedule;
    }

    /**
     * Gets beaconlightingschedule
     * 
     * @return Value for beaconlightingschedule.
     **/
    public String getBeaconlightingschedule() {
        return beaconlightingschedule;
    }

    /**
     * Sets beaconlightingschedule
     * 
     * @param beaconlightingschedule New value for beaconlightingschedule.
     **/
    public void setBeaconlightingschedule(String beaconlightingschedule) {
        this.beaconlightingschedule = beaconlightingschedule;
    }

    /**
     * Gets toweronfield
     * 
     * @return Value for toweronfield.
     **/
    public String getToweronfield() {
        return toweronfield;
    }

    /**
     * Sets toweronfield
     * 
     * @param toweronfield New value for toweronfield.
     **/
    public void setToweronfield(String toweronfield) {
        this.toweronfield = toweronfield;
    }

    /**
     * Gets unicomfrequency
     * 
     * @return Value for unicomfrequency.
     **/
    public String getUnicomfrequency() {
        return unicomfrequency;
    }

    /**
     * Sets unicomfrequency
     * 
     * @param unicomfrequency New value for unicomfrequency.
     **/
    public void setUnicomfrequency(String unicomfrequency) {
        this.unicomfrequency = unicomfrequency;
    }

    /**
     * Gets ctafrequency
     * 
     * @return Value for ctafrequency.
     **/
    public String getCtafrequency() {
        return ctafrequency;
    }

    /**
     * Sets ctafrequency
     * 
     * @param ctafrequency New value for ctafrequency.
     **/
    public void setCtafrequency(String ctafrequency) {
        this.ctafrequency = ctafrequency;
    }

    /**
     * Gets segmentedcircle
     * 
     * @return Value for segmentedcircle.
     **/
    public String getSegmentedcircle() {
        return segmentedcircle;
    }

    /**
     * Sets segmentedcircle
     * 
     * @param segmentedcircle New value for segmentedcircle.
     **/
    public void setSegmentedcircle(String segmentedcircle) {
        this.segmentedcircle = segmentedcircle;
    }

    /**
     * Gets beaconcolor
     * 
     * @return Value for beaconcolor.
     **/
    public String getBeaconcolor() {
        return beaconcolor;
    }

    /**
     * Sets beaconcolor
     * 
     * @param beaconcolor New value for beaconcolor.
     **/
    public void setBeaconcolor(String beaconcolor) {
        this.beaconcolor = beaconcolor;
    }

    /**
     * Gets landingfee
     * 
     * @return Value for landingfee.
     **/
    public String getLandingfee() {
        return landingfee;
    }

    /**
     * Sets landingfee
     * 
     * @param landingfee New value for landingfee.
     **/
    public void setLandingfee(String landingfee) {
        this.landingfee = landingfee;
    }

    /**
     * Gets medicaluse
     * 
     * @return Value for medicaluse.
     **/
    public String getMedicaluse() {
        return medicaluse;
    }

    /**
     * Sets medicaluse
     * 
     * @param medicaluse New value for medicaluse.
     **/
    public void setMedicaluse(String medicaluse) {
        this.medicaluse = medicaluse;
    }

    /**
     * Gets singleengine
     * 
     * @return Value for singleengine.
     **/
    public String getSingleengine() {
        return singleengine;
    }

    /**
     * Sets singleengine
     * 
     * @param singleengine New value for singleengine.
     **/
    public void setSingleengine(String singleengine) {
        this.singleengine = singleengine;
    }

    /**
     * Gets multiengine
     * 
     * @return Value for multiengine.
     **/
    public String getMultiengine() {
        return multiengine;
    }

    /**
     * Sets multiengine
     * 
     * @param multiengine New value for multiengine.
     **/
    public void setMultiengine(String multiengine) {
        this.multiengine = multiengine;
    }

    /**
     * Gets jetengine
     * 
     * @return Value for jetengine.
     **/
    public String getJetengine() {
        return jetengine;
    }

    /**
     * Sets jetengine
     * 
     * @param jetengine New value for jetengine.
     **/
    public void setJetengine(String jetengine) {
        this.jetengine = jetengine;
    }

    /**
     * Gets helicopter
     * 
     * @return Value for helicopter.
     **/
    public String getHelicopter() {
        return helicopter;
    }

    /**
     * Sets helicopter
     * 
     * @param helicopter New value for helicopter.
     **/
    public void setHelicopter(String helicopter) {
        this.helicopter = helicopter;
    }

    /**
     * Gets gliders
     * 
     * @return Value for gliders.
     **/
    public String getGliders() {
        return gliders;
    }

    /**
     * Sets gliders
     * 
     * @param gliders New value for gliders.
     **/
    public void setGliders(String gliders) {
        this.gliders = gliders;
    }

    /**
     * Gets military
     * 
     * @return Value for military.
     **/
    public String getMilitary() {
        return military;
    }

    /**
     * Sets military
     * 
     * @param military New value for military.
     **/
    public void setMilitary(String military) {
        this.military = military;
    }

    /**
     * Gets ultralight
     * 
     * @return Value for ultralight.
     **/
    public String getUltralight() {
        return ultralight;
    }

    /**
     * Sets ultralight
     * 
     * @param ultralight New value for ultralight.
     **/
    public void setUltralight(String ultralight) {
        this.ultralight = ultralight;
    }

    /**
     * Gets commercialservices
     * 
     * @return Value for commercialservices.
     **/
    public String getCommercialservices() {
        return commercialservices;
    }

    /**
     * Sets commercialservices
     * 
     * @param commercialservices New value for commercialservices.
     **/
    public void setCommercialservices(String commercialservices) {
        this.commercialservices = commercialservices;
    }

    /**
     * Gets commuterservices
     * 
     * @return Value for commuterservices.
     **/
    public String getCommuterservices() {
        return commuterservices;
    }

    /**
     * Sets commuterservices
     * 
     * @param commuterservices New value for commuterservices.
     **/
    public void setCommuterservices(String commuterservices) {
        this.commuterservices = commuterservices;
    }

    /**
     * Gets airtaxiservices
     * 
     * @return Value for airtaxiservices.
     **/
    public String getAirtaxiservices() {
        return airtaxiservices;
    }

    /**
     * Sets airtaxiservices
     * 
     * @param airtaxiservices New value for airtaxiservices.
     **/
    public void setAirtaxiservices(String airtaxiservices) {
        this.airtaxiservices = airtaxiservices;
    }

    /**
     * Gets generalaviationlocal
     * 
     * @return Value for generalaviationlocal.
     **/
    public String getGeneralaviationlocal() {
        return generalaviationlocal;
    }

    /**
     * Sets generalaviationlocal
     * 
     * @param generalaviationlocal New value for generalaviationlocal.
     **/
    public void setGeneralaviationlocal(String generalaviationlocal) {
        this.generalaviationlocal = generalaviationlocal;
    }

    /**
     * Gets generalaviationitinerant
     * 
     * @return Value for generalaviationitinerant.
     **/
    public String getGeneralaviationitinerant() {
        return generalaviationitinerant;
    }

    /**
     * Sets generalaviationitinerant
     * 
     * @param generalaviationitinerant New value for generalaviationitinerant.
     **/
    public void setGeneralaviationitinerant(String generalaviationitinerant) {
        this.generalaviationitinerant = generalaviationitinerant;
    }

    /**
     * Gets militaryoperations
     * 
     * @return Value for militaryoperations.
     **/
    public String getMilitaryoperations() {
        return militaryoperations;
    }

    /**
     * Sets militaryoperations
     * 
     * @param militaryoperations New value for militaryoperations.
     **/
    public void setMilitaryoperations(String militaryoperations) {
        this.militaryoperations = militaryoperations;
    }

    /**
     * Gets operationsdataexpires
     * 
     * @return Value for operationsdataexpires.
     **/
    public Date getOperationsdataexpires() {
        return operationsdataexpires;
    }

    /**
     * Sets operationsdataexpires
     * 
     * @param operationsdataexpires New value for operationsdataexpires.
     **/
    public void setOperationsdataexpires(Date operationsdataexpires) {
        this.operationsdataexpires = operationsdataexpires;
    }

    /**
     * Gets positionsource
     * 
     * @return Value for positionsource.
     **/
    public String getPositionsource() {
        return positionsource;
    }

    /**
     * Sets positionsource
     * 
     * @param positionsource New value for positionsource.
     **/
    public void setPositionsource(String positionsource) {
        this.positionsource = positionsource;
    }

    /**
     * Gets positionsourcedate
     * 
     * @return Value for positionsourcedate.
     **/
    public Timestamp getPositionsourcedate() {
        return positionsourcedate;
    }

    /**
     * Sets positionsourcedate
     * 
     * @param positionsourcedate New value for positionsourcedate.
     **/
    public void setPositionsourcedate(Timestamp positionsourcedate) {
        this.positionsourcedate = positionsourcedate;
    }

    /**
     * Gets elevationsource
     * 
     * @return Value for elevationsource.
     **/
    public String getElevationsource() {
        return elevationsource;
    }

    /**
     * Sets elevationsource
     * 
     * @param elevationsource New value for elevationsource.
     **/
    public void setElevationsource(String elevationsource) {
        this.elevationsource = elevationsource;
    }

    /**
     * Gets elevationsourcedate
     * 
     * @return Value for elevationsourcedate.
     **/
    public Timestamp getElevationsourcedate() {
        return elevationsourcedate;
    }

    /**
     * Sets elevationsourcedate
     * 
     * @param elevationsourcedate New value for elevationsourcedate.
     **/
    public void setElevationsourcedate(Timestamp elevationsourcedate) {
        this.elevationsourcedate = elevationsourcedate;
    }

    /**
     * Gets contractfuel
     * 
     * @return Value for contractfuel.
     **/
    public String getContractfuel() {
        return contractfuel;
    }

    /**
     * Sets contractfuel
     * 
     * @param contractfuel New value for contractfuel.
     **/
    public void setContractfuel(String contractfuel) {
        this.contractfuel = contractfuel;
    }

    /**
     * Gets transientstorage
     * 
     * @return Value for transientstorage.
     **/
    public String getTransientstorage() {
        return transientstorage;
    }

    /**
     * Sets transientstorage
     * 
     * @param transientstorage New value for transientstorage.
     **/
    public void setTransientstorage(String transientstorage) {
        this.transientstorage = transientstorage;
    }

    /**
     * Gets otherservices
     * 
     * @return Value for otherservices.
     **/
    public String getOtherservices() {
        return otherservices;
    }

    /**
     * Sets otherservices
     * 
     * @param otherservices New value for otherservices.
     **/
    public void setOtherservices(String otherservices) {
        this.otherservices = otherservices;
    }

    /**
     * Gets windsock
     * 
     * @return Value for windsock.
     **/
    public String getWindsock() {
        return windsock;
    }

    /**
     * Sets windsock
     * 
     * @param windsock New value for windsock.
     **/
    public void setWindsock(String windsock) {
        this.windsock = windsock;
    }

    /**
     * Gets icao
     * 
     * @return Value for icao.
     **/
    public String getIcao() {
        return icao;
    }

    /**
     * Sets icao
     * 
     * @param icao New value for icao.
     **/
    public void setIcao(String icao) {
        this.icao = icao;
    }

    /**
     * Gets latitude
     * 
     * @return Value for latitude.
     **/
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets latitude
     * 
     * @param latitude New value for latitude.
     **/
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * Gets longitude
     * 
     * @return Value for longitude.
     **/
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets longitude
     * 
     * @param longitude New value for longitude.
     **/
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * Gets isserviced
     * 
     * @return Value for isserviced.
     **/
    public Boolean getIsserviced() {
        return isserviced;
    }

    /**
     * Sets isserviced
     * 
     * @param isserviced New value for isserviced.
     **/
    public void setIsserviced(Boolean isserviced) {
        this.isserviced = isserviced;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Airports))
            return false;
        
        Airports that = (Airports)o;

        if (recordtypeindicator != null ? !recordtypeindicator.equals(that.recordtypeindicator) : that.recordtypeindicator != null)
            return false;
        

        if (sitenumber != null ? !sitenumber.equals(that.sitenumber) : that.sitenumber != null)
            return false;
        

        if (facilitytype != null ? !facilitytype.equals(that.facilitytype) : that.facilitytype != null)
            return false;
        

        if (locationidentifier != null ? !locationidentifier.equals(that.locationidentifier) : that.locationidentifier != null)
            return false;
        

        if (infoeffectivedate != null ? !infoeffectivedate.equals(that.infoeffectivedate) : that.infoeffectivedate != null)
            return false;
        

        if (faaregioncode != null ? !faaregioncode.equals(that.faaregioncode) : that.faaregioncode != null)
            return false;
        

        if (faafieldofficecode != null ? !faafieldofficecode.equals(that.faafieldofficecode) : that.faafieldofficecode != null)
            return false;
        

        if (stateabbr != null ? !stateabbr.equals(that.stateabbr) : that.stateabbr != null)
            return false;
        

        if (statename != null ? !statename.equals(that.statename) : that.statename != null)
            return false;
        

        if (county != null ? !county.equals(that.county) : that.county != null)
            return false;
        

        if (countystatename != null ? !countystatename.equals(that.countystatename) : that.countystatename != null)
            return false;
        

        if (city != null ? !city.equals(that.city) : that.city != null)
            return false;
        

        if (facilityname != null ? !facilityname.equals(that.facilityname) : that.facilityname != null)
            return false;
        

        if (ownershiptype != null ? !ownershiptype.equals(that.ownershiptype) : that.ownershiptype != null)
            return false;
        

        if (facilityuse != null ? !facilityuse.equals(that.facilityuse) : that.facilityuse != null)
            return false;
        

        if (ownername != null ? !ownername.equals(that.ownername) : that.ownername != null)
            return false;
        

        if (owneraddress != null ? !owneraddress.equals(that.owneraddress) : that.owneraddress != null)
            return false;
        

        if (ownercitystatezip != null ? !ownercitystatezip.equals(that.ownercitystatezip) : that.ownercitystatezip != null)
            return false;
        

        if (ownerphone != null ? !ownerphone.equals(that.ownerphone) : that.ownerphone != null)
            return false;
        

        if (managername != null ? !managername.equals(that.managername) : that.managername != null)
            return false;
        

        if (manageraddress != null ? !manageraddress.equals(that.manageraddress) : that.manageraddress != null)
            return false;
        

        if (managercitystatezip != null ? !managercitystatezip.equals(that.managercitystatezip) : that.managercitystatezip != null)
            return false;
        

        if (managerphone != null ? !managerphone.equals(that.managerphone) : that.managerphone != null)
            return false;
        

        if (referencepointlatitudef != null ? !referencepointlatitudef.equals(that.referencepointlatitudef) : that.referencepointlatitudef != null)
            return false;
        

        if (referencepointlatitudes != null ? !referencepointlatitudes.equals(that.referencepointlatitudes) : that.referencepointlatitudes != null)
            return false;
        

        if (referencepointlongitudef != null ? !referencepointlongitudef.equals(that.referencepointlongitudef) : that.referencepointlongitudef != null)
            return false;
        

        if (referencepointlongitudes != null ? !referencepointlongitudes.equals(that.referencepointlongitudes) : that.referencepointlongitudes != null)
            return false;
        

        if (referencepointmethod != null ? !referencepointmethod.equals(that.referencepointmethod) : that.referencepointmethod != null)
            return false;
        

        if (airportelevation != null ? !airportelevation.equals(that.airportelevation) : that.airportelevation != null)
            return false;
        

        if (airportelevationmethod != null ? !airportelevationmethod.equals(that.airportelevationmethod) : that.airportelevationmethod != null)
            return false;
        

        if (magneticvariation != null ? !magneticvariation.equals(that.magneticvariation) : that.magneticvariation != null)
            return false;
        

        if (magneticvariationepoch != null ? !magneticvariationepoch.equals(that.magneticvariationepoch) : that.magneticvariationepoch != null)
            return false;
        

        if (trafficpatternaltitude != null ? !trafficpatternaltitude.equals(that.trafficpatternaltitude) : that.trafficpatternaltitude != null)
            return false;
        

        if (sectionalname != null ? !sectionalname.equals(that.sectionalname) : that.sectionalname != null)
            return false;
        

        if (distancefromcity != null ? !distancefromcity.equals(that.distancefromcity) : that.distancefromcity != null)
            return false;
        

        if (directiontocity != null ? !directiontocity.equals(that.directiontocity) : that.directiontocity != null)
            return false;
        

        if (citydistrict != null ? !citydistrict.equals(that.citydistrict) : that.citydistrict != null)
            return false;
        

        if (airportacres != null ? !airportacres.equals(that.airportacres) : that.airportacres != null)
            return false;
        

        if (artccidentifier != null ? !artccidentifier.equals(that.artccidentifier) : that.artccidentifier != null)
            return false;
        

        if (artcccomputeridentifier != null ? !artcccomputeridentifier.equals(that.artcccomputeridentifier) : that.artcccomputeridentifier != null)
            return false;
        

        if (artccname != null ? !artccname.equals(that.artccname) : that.artccname != null)
            return false;
        

        if (responsibleartccidentifier != null ? !responsibleartccidentifier.equals(that.responsibleartccidentifier) : that.responsibleartccidentifier != null)
            return false;
        

        if (responsibleartccname != null ? !responsibleartccname.equals(that.responsibleartccname) : that.responsibleartccname != null)
            return false;
        

        if (tieinfssonfield != null ? !tieinfssonfield.equals(that.tieinfssonfield) : that.tieinfssonfield != null)
            return false;
        

        if (tieinfssidentifier != null ? !tieinfssidentifier.equals(that.tieinfssidentifier) : that.tieinfssidentifier != null)
            return false;
        

        if (tieinfssname != null ? !tieinfssname.equals(that.tieinfssname) : that.tieinfssname != null)
            return false;
        

        if (fssphonenumber != null ? !fssphonenumber.equals(that.fssphonenumber) : that.fssphonenumber != null)
            return false;
        

        if (fsstollfreephone != null ? !fsstollfreephone.equals(that.fsstollfreephone) : that.fsstollfreephone != null)
            return false;
        

        if (alternatefssidentifier != null ? !alternatefssidentifier.equals(that.alternatefssidentifier) : that.alternatefssidentifier != null)
            return false;
        

        if (alternatefssname != null ? !alternatefssname.equals(that.alternatefssname) : that.alternatefssname != null)
            return false;
        

        if (alternatefsstollfree != null ? !alternatefsstollfree.equals(that.alternatefsstollfree) : that.alternatefsstollfree != null)
            return false;
        

        if (notamfacilityidentifier != null ? !notamfacilityidentifier.equals(that.notamfacilityidentifier) : that.notamfacilityidentifier != null)
            return false;
        

        if (notamdavailable != null ? !notamdavailable.equals(that.notamdavailable) : that.notamdavailable != null)
            return false;
        

        if (airportactivationdate != null ? !airportactivationdate.equals(that.airportactivationdate) : that.airportactivationdate != null)
            return false;
        

        if (airportstatuscode != null ? !airportstatuscode.equals(that.airportstatuscode) : that.airportstatuscode != null)
            return false;
        

        if (airportarffcert != null ? !airportarffcert.equals(that.airportarffcert) : that.airportarffcert != null)
            return false;
        

        if (agreementcode != null ? !agreementcode.equals(that.agreementcode) : that.agreementcode != null)
            return false;
        

        if (airspaceanalysis != null ? !airspaceanalysis.equals(that.airspaceanalysis) : that.airspaceanalysis != null)
            return false;
        

        if (international != null ? !international.equals(that.international) : that.international != null)
            return false;
        

        if (offfieldcustoms != null ? !offfieldcustoms.equals(that.offfieldcustoms) : that.offfieldcustoms != null)
            return false;
        

        if (militaryjointuse != null ? !militaryjointuse.equals(that.militaryjointuse) : that.militaryjointuse != null)
            return false;
        

        if (militarylandingrights != null ? !militarylandingrights.equals(that.militarylandingrights) : that.militarylandingrights != null)
            return false;
        

        if (inspectionmethod != null ? !inspectionmethod.equals(that.inspectionmethod) : that.inspectionmethod != null)
            return false;
        

        if (inspectionagency != null ? !inspectionagency.equals(that.inspectionagency) : that.inspectionagency != null)
            return false;
        

        if (lastinspection != null ? !lastinspection.equals(that.lastinspection) : that.lastinspection != null)
            return false;
        

        if (lastinformationrequest != null ? !lastinformationrequest.equals(that.lastinformationrequest) : that.lastinformationrequest != null)
            return false;
        

        if (fueltypes != null ? !fueltypes.equals(that.fueltypes) : that.fueltypes != null)
            return false;
        

        if (airframerepair != null ? !airframerepair.equals(that.airframerepair) : that.airframerepair != null)
            return false;
        

        if (powerplantrepair != null ? !powerplantrepair.equals(that.powerplantrepair) : that.powerplantrepair != null)
            return false;
        

        if (bottledoxygen != null ? !bottledoxygen.equals(that.bottledoxygen) : that.bottledoxygen != null)
            return false;
        

        if (bulkoxygen != null ? !bulkoxygen.equals(that.bulkoxygen) : that.bulkoxygen != null)
            return false;
        

        if (lightingschedule != null ? !lightingschedule.equals(that.lightingschedule) : that.lightingschedule != null)
            return false;
        

        if (beaconlightingschedule != null ? !beaconlightingschedule.equals(that.beaconlightingschedule) : that.beaconlightingschedule != null)
            return false;
        

        if (toweronfield != null ? !toweronfield.equals(that.toweronfield) : that.toweronfield != null)
            return false;
        

        if (unicomfrequency != null ? !unicomfrequency.equals(that.unicomfrequency) : that.unicomfrequency != null)
            return false;
        

        if (ctafrequency != null ? !ctafrequency.equals(that.ctafrequency) : that.ctafrequency != null)
            return false;
        

        if (segmentedcircle != null ? !segmentedcircle.equals(that.segmentedcircle) : that.segmentedcircle != null)
            return false;
        

        if (beaconcolor != null ? !beaconcolor.equals(that.beaconcolor) : that.beaconcolor != null)
            return false;
        

        if (landingfee != null ? !landingfee.equals(that.landingfee) : that.landingfee != null)
            return false;
        

        if (medicaluse != null ? !medicaluse.equals(that.medicaluse) : that.medicaluse != null)
            return false;
        

        if (singleengine != null ? !singleengine.equals(that.singleengine) : that.singleengine != null)
            return false;
        

        if (multiengine != null ? !multiengine.equals(that.multiengine) : that.multiengine != null)
            return false;
        

        if (jetengine != null ? !jetengine.equals(that.jetengine) : that.jetengine != null)
            return false;
        

        if (helicopter != null ? !helicopter.equals(that.helicopter) : that.helicopter != null)
            return false;
        

        if (gliders != null ? !gliders.equals(that.gliders) : that.gliders != null)
            return false;
        

        if (military != null ? !military.equals(that.military) : that.military != null)
            return false;
        

        if (ultralight != null ? !ultralight.equals(that.ultralight) : that.ultralight != null)
            return false;
        

        if (commercialservices != null ? !commercialservices.equals(that.commercialservices) : that.commercialservices != null)
            return false;
        

        if (commuterservices != null ? !commuterservices.equals(that.commuterservices) : that.commuterservices != null)
            return false;
        

        if (airtaxiservices != null ? !airtaxiservices.equals(that.airtaxiservices) : that.airtaxiservices != null)
            return false;
        

        if (generalaviationlocal != null ? !generalaviationlocal.equals(that.generalaviationlocal) : that.generalaviationlocal != null)
            return false;
        

        if (generalaviationitinerant != null ? !generalaviationitinerant.equals(that.generalaviationitinerant) : that.generalaviationitinerant != null)
            return false;
        

        if (militaryoperations != null ? !militaryoperations.equals(that.militaryoperations) : that.militaryoperations != null)
            return false;
        

        if (operationsdataexpires != null ? !operationsdataexpires.equals(that.operationsdataexpires) : that.operationsdataexpires != null)
            return false;
        

        if (positionsource != null ? !positionsource.equals(that.positionsource) : that.positionsource != null)
            return false;
        

        if (positionsourcedate != null ? !positionsourcedate.equals(that.positionsourcedate) : that.positionsourcedate != null)
            return false;
        

        if (elevationsource != null ? !elevationsource.equals(that.elevationsource) : that.elevationsource != null)
            return false;
        

        if (elevationsourcedate != null ? !elevationsourcedate.equals(that.elevationsourcedate) : that.elevationsourcedate != null)
            return false;
        

        if (contractfuel != null ? !contractfuel.equals(that.contractfuel) : that.contractfuel != null)
            return false;
        

        if (transientstorage != null ? !transientstorage.equals(that.transientstorage) : that.transientstorage != null)
            return false;
        

        if (otherservices != null ? !otherservices.equals(that.otherservices) : that.otherservices != null)
            return false;
        

        if (windsock != null ? !windsock.equals(that.windsock) : that.windsock != null)
            return false;
        

        if (icao != null ? !icao.equals(that.icao) : that.icao != null)
            return false;
        

        if (latitude != null ? !latitude.equals(that.latitude) : that.latitude != null)
            return false;
        

        if (longitude != null ? !longitude.equals(that.longitude) : that.longitude != null)
            return false;
        

        if (isserviced != null ? !isserviced.equals(that.isserviced) : that.isserviced != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = recordtypeindicator != null ? recordtypeindicator.hashCode() : 0;

        res = 31 * res + (sitenumber != null ? sitenumber.hashCode() : 0);

        res = 31 * res + (facilitytype != null ? facilitytype.hashCode() : 0);

        res = 31 * res + (locationidentifier != null ? locationidentifier.hashCode() : 0);

        res = 31 * res + (infoeffectivedate != null ? infoeffectivedate.hashCode() : 0);

        res = 31 * res + (faaregioncode != null ? faaregioncode.hashCode() : 0);

        res = 31 * res + (faafieldofficecode != null ? faafieldofficecode.hashCode() : 0);

        res = 31 * res + (stateabbr != null ? stateabbr.hashCode() : 0);

        res = 31 * res + (statename != null ? statename.hashCode() : 0);

        res = 31 * res + (county != null ? county.hashCode() : 0);

        res = 31 * res + (countystatename != null ? countystatename.hashCode() : 0);

        res = 31 * res + (city != null ? city.hashCode() : 0);

        res = 31 * res + (facilityname != null ? facilityname.hashCode() : 0);

        res = 31 * res + (ownershiptype != null ? ownershiptype.hashCode() : 0);

        res = 31 * res + (facilityuse != null ? facilityuse.hashCode() : 0);

        res = 31 * res + (ownername != null ? ownername.hashCode() : 0);

        res = 31 * res + (owneraddress != null ? owneraddress.hashCode() : 0);

        res = 31 * res + (ownercitystatezip != null ? ownercitystatezip.hashCode() : 0);

        res = 31 * res + (ownerphone != null ? ownerphone.hashCode() : 0);

        res = 31 * res + (managername != null ? managername.hashCode() : 0);

        res = 31 * res + (manageraddress != null ? manageraddress.hashCode() : 0);

        res = 31 * res + (managercitystatezip != null ? managercitystatezip.hashCode() : 0);

        res = 31 * res + (managerphone != null ? managerphone.hashCode() : 0);

        res = 31 * res + (referencepointlatitudef != null ? referencepointlatitudef.hashCode() : 0);

        res = 31 * res + (referencepointlatitudes != null ? referencepointlatitudes.hashCode() : 0);

        res = 31 * res + (referencepointlongitudef != null ? referencepointlongitudef.hashCode() : 0);

        res = 31 * res + (referencepointlongitudes != null ? referencepointlongitudes.hashCode() : 0);

        res = 31 * res + (referencepointmethod != null ? referencepointmethod.hashCode() : 0);

        res = 31 * res + (airportelevation != null ? airportelevation.hashCode() : 0);

        res = 31 * res + (airportelevationmethod != null ? airportelevationmethod.hashCode() : 0);

        res = 31 * res + (magneticvariation != null ? magneticvariation.hashCode() : 0);

        res = 31 * res + (magneticvariationepoch != null ? magneticvariationepoch.hashCode() : 0);

        res = 31 * res + (trafficpatternaltitude != null ? trafficpatternaltitude.hashCode() : 0);

        res = 31 * res + (sectionalname != null ? sectionalname.hashCode() : 0);

        res = 31 * res + (distancefromcity != null ? distancefromcity.hashCode() : 0);

        res = 31 * res + (directiontocity != null ? directiontocity.hashCode() : 0);

        res = 31 * res + (citydistrict != null ? citydistrict.hashCode() : 0);

        res = 31 * res + (airportacres != null ? airportacres.hashCode() : 0);

        res = 31 * res + (artccidentifier != null ? artccidentifier.hashCode() : 0);

        res = 31 * res + (artcccomputeridentifier != null ? artcccomputeridentifier.hashCode() : 0);

        res = 31 * res + (artccname != null ? artccname.hashCode() : 0);

        res = 31 * res + (responsibleartccidentifier != null ? responsibleartccidentifier.hashCode() : 0);

        res = 31 * res + (responsibleartccname != null ? responsibleartccname.hashCode() : 0);

        res = 31 * res + (tieinfssonfield != null ? tieinfssonfield.hashCode() : 0);

        res = 31 * res + (tieinfssidentifier != null ? tieinfssidentifier.hashCode() : 0);

        res = 31 * res + (tieinfssname != null ? tieinfssname.hashCode() : 0);

        res = 31 * res + (fssphonenumber != null ? fssphonenumber.hashCode() : 0);

        res = 31 * res + (fsstollfreephone != null ? fsstollfreephone.hashCode() : 0);

        res = 31 * res + (alternatefssidentifier != null ? alternatefssidentifier.hashCode() : 0);

        res = 31 * res + (alternatefssname != null ? alternatefssname.hashCode() : 0);

        res = 31 * res + (alternatefsstollfree != null ? alternatefsstollfree.hashCode() : 0);

        res = 31 * res + (notamfacilityidentifier != null ? notamfacilityidentifier.hashCode() : 0);

        res = 31 * res + (notamdavailable != null ? notamdavailable.hashCode() : 0);

        res = 31 * res + (airportactivationdate != null ? airportactivationdate.hashCode() : 0);

        res = 31 * res + (airportstatuscode != null ? airportstatuscode.hashCode() : 0);

        res = 31 * res + (airportarffcert != null ? airportarffcert.hashCode() : 0);

        res = 31 * res + (agreementcode != null ? agreementcode.hashCode() : 0);

        res = 31 * res + (airspaceanalysis != null ? airspaceanalysis.hashCode() : 0);

        res = 31 * res + (international != null ? international.hashCode() : 0);

        res = 31 * res + (offfieldcustoms != null ? offfieldcustoms.hashCode() : 0);

        res = 31 * res + (militaryjointuse != null ? militaryjointuse.hashCode() : 0);

        res = 31 * res + (militarylandingrights != null ? militarylandingrights.hashCode() : 0);

        res = 31 * res + (inspectionmethod != null ? inspectionmethod.hashCode() : 0);

        res = 31 * res + (inspectionagency != null ? inspectionagency.hashCode() : 0);

        res = 31 * res + (lastinspection != null ? lastinspection.hashCode() : 0);

        res = 31 * res + (lastinformationrequest != null ? lastinformationrequest.hashCode() : 0);

        res = 31 * res + (fueltypes != null ? fueltypes.hashCode() : 0);

        res = 31 * res + (airframerepair != null ? airframerepair.hashCode() : 0);

        res = 31 * res + (powerplantrepair != null ? powerplantrepair.hashCode() : 0);

        res = 31 * res + (bottledoxygen != null ? bottledoxygen.hashCode() : 0);

        res = 31 * res + (bulkoxygen != null ? bulkoxygen.hashCode() : 0);

        res = 31 * res + (lightingschedule != null ? lightingschedule.hashCode() : 0);

        res = 31 * res + (beaconlightingschedule != null ? beaconlightingschedule.hashCode() : 0);

        res = 31 * res + (toweronfield != null ? toweronfield.hashCode() : 0);

        res = 31 * res + (unicomfrequency != null ? unicomfrequency.hashCode() : 0);

        res = 31 * res + (ctafrequency != null ? ctafrequency.hashCode() : 0);

        res = 31 * res + (segmentedcircle != null ? segmentedcircle.hashCode() : 0);

        res = 31 * res + (beaconcolor != null ? beaconcolor.hashCode() : 0);

        res = 31 * res + (landingfee != null ? landingfee.hashCode() : 0);

        res = 31 * res + (medicaluse != null ? medicaluse.hashCode() : 0);

        res = 31 * res + (singleengine != null ? singleengine.hashCode() : 0);

        res = 31 * res + (multiengine != null ? multiengine.hashCode() : 0);

        res = 31 * res + (jetengine != null ? jetengine.hashCode() : 0);

        res = 31 * res + (helicopter != null ? helicopter.hashCode() : 0);

        res = 31 * res + (gliders != null ? gliders.hashCode() : 0);

        res = 31 * res + (military != null ? military.hashCode() : 0);

        res = 31 * res + (ultralight != null ? ultralight.hashCode() : 0);

        res = 31 * res + (commercialservices != null ? commercialservices.hashCode() : 0);

        res = 31 * res + (commuterservices != null ? commuterservices.hashCode() : 0);

        res = 31 * res + (airtaxiservices != null ? airtaxiservices.hashCode() : 0);

        res = 31 * res + (generalaviationlocal != null ? generalaviationlocal.hashCode() : 0);

        res = 31 * res + (generalaviationitinerant != null ? generalaviationitinerant.hashCode() : 0);

        res = 31 * res + (militaryoperations != null ? militaryoperations.hashCode() : 0);

        res = 31 * res + (operationsdataexpires != null ? operationsdataexpires.hashCode() : 0);

        res = 31 * res + (positionsource != null ? positionsource.hashCode() : 0);

        res = 31 * res + (positionsourcedate != null ? positionsourcedate.hashCode() : 0);

        res = 31 * res + (elevationsource != null ? elevationsource.hashCode() : 0);

        res = 31 * res + (elevationsourcedate != null ? elevationsourcedate.hashCode() : 0);

        res = 31 * res + (contractfuel != null ? contractfuel.hashCode() : 0);

        res = 31 * res + (transientstorage != null ? transientstorage.hashCode() : 0);

        res = 31 * res + (otherservices != null ? otherservices.hashCode() : 0);

        res = 31 * res + (windsock != null ? windsock.hashCode() : 0);

        res = 31 * res + (icao != null ? icao.hashCode() : 0);

        res = 31 * res + (latitude != null ? latitude.hashCode() : 0);

        res = 31 * res + (longitude != null ? longitude.hashCode() : 0);

        res = 31 * res + (isserviced != null ? isserviced.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Airports [" + 
            "recordtypeindicator=" + recordtypeindicator + ", " + 
            "sitenumber=" + sitenumber + ", " + 
            "facilitytype=" + facilitytype + ", " + 
            "locationidentifier=" + locationidentifier + ", " + 
            "infoeffectivedate=" + infoeffectivedate + ", " + 
            "faaregioncode=" + faaregioncode + ", " + 
            "faafieldofficecode=" + faafieldofficecode + ", " + 
            "stateabbr=" + stateabbr + ", " + 
            "statename=" + statename + ", " + 
            "county=" + county + ", " + 
            "countystatename=" + countystatename + ", " + 
            "city=" + city + ", " + 
            "facilityname=" + facilityname + ", " + 
            "ownershiptype=" + ownershiptype + ", " + 
            "facilityuse=" + facilityuse + ", " + 
            "ownername=" + ownername + ", " + 
            "owneraddress=" + owneraddress + ", " + 
            "ownercitystatezip=" + ownercitystatezip + ", " + 
            "ownerphone=" + ownerphone + ", " + 
            "managername=" + managername + ", " + 
            "manageraddress=" + manageraddress + ", " + 
            "managercitystatezip=" + managercitystatezip + ", " + 
            "managerphone=" + managerphone + ", " + 
            "referencepointlatitudef=" + referencepointlatitudef + ", " + 
            "referencepointlatitudes=" + referencepointlatitudes + ", " + 
            "referencepointlongitudef=" + referencepointlongitudef + ", " + 
            "referencepointlongitudes=" + referencepointlongitudes + ", " + 
            "referencepointmethod=" + referencepointmethod + ", " + 
            "airportelevation=" + airportelevation + ", " + 
            "airportelevationmethod=" + airportelevationmethod + ", " + 
            "magneticvariation=" + magneticvariation + ", " + 
            "magneticvariationepoch=" + magneticvariationepoch + ", " + 
            "trafficpatternaltitude=" + trafficpatternaltitude + ", " + 
            "sectionalname=" + sectionalname + ", " + 
            "distancefromcity=" + distancefromcity + ", " + 
            "directiontocity=" + directiontocity + ", " + 
            "citydistrict=" + citydistrict + ", " + 
            "airportacres=" + airportacres + ", " + 
            "artccidentifier=" + artccidentifier + ", " + 
            "artcccomputeridentifier=" + artcccomputeridentifier + ", " + 
            "artccname=" + artccname + ", " + 
            "responsibleartccidentifier=" + responsibleartccidentifier + ", " + 
            "responsibleartccname=" + responsibleartccname + ", " + 
            "tieinfssonfield=" + tieinfssonfield + ", " + 
            "tieinfssidentifier=" + tieinfssidentifier + ", " + 
            "tieinfssname=" + tieinfssname + ", " + 
            "fssphonenumber=" + fssphonenumber + ", " + 
            "fsstollfreephone=" + fsstollfreephone + ", " + 
            "alternatefssidentifier=" + alternatefssidentifier + ", " + 
            "alternatefssname=" + alternatefssname + ", " + 
            "alternatefsstollfree=" + alternatefsstollfree + ", " + 
            "notamfacilityidentifier=" + notamfacilityidentifier + ", " + 
            "notamdavailable=" + notamdavailable + ", " + 
            "airportactivationdate=" + airportactivationdate + ", " + 
            "airportstatuscode=" + airportstatuscode + ", " + 
            "airportarffcert=" + airportarffcert + ", " + 
            "agreementcode=" + agreementcode + ", " + 
            "airspaceanalysis=" + airspaceanalysis + ", " + 
            "international=" + international + ", " + 
            "offfieldcustoms=" + offfieldcustoms + ", " + 
            "militaryjointuse=" + militaryjointuse + ", " + 
            "militarylandingrights=" + militarylandingrights + ", " + 
            "inspectionmethod=" + inspectionmethod + ", " + 
            "inspectionagency=" + inspectionagency + ", " + 
            "lastinspection=" + lastinspection + ", " + 
            "lastinformationrequest=" + lastinformationrequest + ", " + 
            "fueltypes=" + fueltypes + ", " + 
            "airframerepair=" + airframerepair + ", " + 
            "powerplantrepair=" + powerplantrepair + ", " + 
            "bottledoxygen=" + bottledoxygen + ", " + 
            "bulkoxygen=" + bulkoxygen + ", " + 
            "lightingschedule=" + lightingschedule + ", " + 
            "beaconlightingschedule=" + beaconlightingschedule + ", " + 
            "toweronfield=" + toweronfield + ", " + 
            "unicomfrequency=" + unicomfrequency + ", " + 
            "ctafrequency=" + ctafrequency + ", " + 
            "segmentedcircle=" + segmentedcircle + ", " + 
            "beaconcolor=" + beaconcolor + ", " + 
            "landingfee=" + landingfee + ", " + 
            "medicaluse=" + medicaluse + ", " + 
            "singleengine=" + singleengine + ", " + 
            "multiengine=" + multiengine + ", " + 
            "jetengine=" + jetengine + ", " + 
            "helicopter=" + helicopter + ", " + 
            "gliders=" + gliders + ", " + 
            "military=" + military + ", " + 
            "ultralight=" + ultralight + ", " + 
            "commercialservices=" + commercialservices + ", " + 
            "commuterservices=" + commuterservices + ", " + 
            "airtaxiservices=" + airtaxiservices + ", " + 
            "generalaviationlocal=" + generalaviationlocal + ", " + 
            "generalaviationitinerant=" + generalaviationitinerant + ", " + 
            "militaryoperations=" + militaryoperations + ", " + 
            "operationsdataexpires=" + operationsdataexpires + ", " + 
            "positionsource=" + positionsource + ", " + 
            "positionsourcedate=" + positionsourcedate + ", " + 
            "elevationsource=" + elevationsource + ", " + 
            "elevationsourcedate=" + elevationsourcedate + ", " + 
            "contractfuel=" + contractfuel + ", " + 
            "transientstorage=" + transientstorage + ", " + 
            "otherservices=" + otherservices + ", " + 
            "windsock=" + windsock + ", " + 
            "icao=" + icao + ", " + 
            "latitude=" + latitude + ", " + 
            "longitude=" + longitude + ", " + 
            "isserviced=" + isserviced +
        "]";
    }
}