package com.pluralsight.duckair.model;

import java.io.Serializable;
import java.sql.Date;

/**
 * Crew definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class Crew implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for crewType. */
    private String crewType;

    /** Value for firstName. */
    private String firstName;

    /** Value for lastName. */
    private String lastName;

    /** Value for employeeId. */
    private String employeeId;

    /** Value for hireDate. */
    private Date hireDate;

    /** Empty constructor. **/
    public Crew() {
        // No-op.
    }

    /** Full constructor. **/
    public Crew(String crewType,
        String firstName,
        String lastName,
        String employeeId,
        Date hireDate) {
        this.crewType = crewType;
        this.firstName = firstName;
        this.lastName = lastName;
        this.employeeId = employeeId;
        this.hireDate = hireDate;
    }

    /**
     * Gets crewType
     * 
     * @return Value for crewType.
     **/
    public String getCrewType() {
        return crewType;
    }

    /**
     * Sets crewType
     * 
     * @param crewType New value for crewType.
     **/
    public void setCrewType(String crewType) {
        this.crewType = crewType;
    }

    /**
     * Gets firstName
     * 
     * @return Value for firstName.
     **/
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets firstName
     * 
     * @param firstName New value for firstName.
     **/
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Gets lastName
     * 
     * @return Value for lastName.
     **/
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets lastName
     * 
     * @param lastName New value for lastName.
     **/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Gets employeeId
     * 
     * @return Value for employeeId.
     **/
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * Sets employeeId
     * 
     * @param employeeId New value for employeeId.
     **/
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * Gets hireDate
     * 
     * @return Value for hireDate.
     **/
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * Sets hireDate
     * 
     * @param hireDate New value for hireDate.
     **/
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Crew))
            return false;
        
        Crew that = (Crew)o;

        if (crewType != null ? !crewType.equals(that.crewType) : that.crewType != null)
            return false;
        

        if (firstName != null ? !firstName.equals(that.firstName) : that.firstName != null)
            return false;
        

        if (lastName != null ? !lastName.equals(that.lastName) : that.lastName != null)
            return false;
        

        if (employeeId != null ? !employeeId.equals(that.employeeId) : that.employeeId != null)
            return false;
        

        if (hireDate != null ? !hireDate.equals(that.hireDate) : that.hireDate != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = crewType != null ? crewType.hashCode() : 0;

        res = 31 * res + (firstName != null ? firstName.hashCode() : 0);

        res = 31 * res + (lastName != null ? lastName.hashCode() : 0);

        res = 31 * res + (employeeId != null ? employeeId.hashCode() : 0);

        res = 31 * res + (hireDate != null ? hireDate.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Crew [" + 
            "crewType=" + crewType + ", " + 
            "firstName=" + firstName + ", " + 
            "lastName=" + lastName + ", " + 
            "employeeId=" + employeeId + ", " + 
            "hireDate=" + hireDate +
        "]";
    }
}