package com.pluralsight.duckair.model;

import java.io.Serializable;

/**
 * Customers definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class Customers implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for firstName. */
    private String firstName;

    /** Value for lastName. */
    private String lastName;

    /** Value for emailAddress. */
    private String emailAddress;

    /** Value for address1. */
    private String address1;

    /** Value for address2. */
    private String address2;

    /** Value for city. */
    private String city;

    /** Value for state. */
    private String state;

    /** Value for zip. */
    private String zip;

    /** Empty constructor. **/
    public Customers() {
        // No-op.
    }

    /** Full constructor. **/
    public Customers(String firstName,
        String lastName,
        String emailAddress,
        String address1,
        String address2,
        String city,
        String state,
        String zip) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddress = emailAddress;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.zip = zip;
    }

    /**
     * Gets firstName
     * 
     * @return Value for firstName.
     **/
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets firstName
     * 
     * @param firstName New value for firstName.
     **/
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Gets lastName
     * 
     * @return Value for lastName.
     **/
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets lastName
     * 
     * @param lastName New value for lastName.
     **/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Gets emailAddress
     * 
     * @return Value for emailAddress.
     **/
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets emailAddress
     * 
     * @param emailAddress New value for emailAddress.
     **/
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * Gets address1
     * 
     * @return Value for address1.
     **/
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets address1
     * 
     * @param address1 New value for address1.
     **/
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * Gets address2
     * 
     * @return Value for address2.
     **/
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets address2
     * 
     * @param address2 New value for address2.
     **/
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * Gets city
     * 
     * @return Value for city.
     **/
    public String getCity() {
        return city;
    }

    /**
     * Sets city
     * 
     * @param city New value for city.
     **/
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Gets state
     * 
     * @return Value for state.
     **/
    public String getState() {
        return state;
    }

    /**
     * Sets state
     * 
     * @param state New value for state.
     **/
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Gets zip
     * 
     * @return Value for zip.
     **/
    public String getZip() {
        return zip;
    }

    /**
     * Sets zip
     * 
     * @param zip New value for zip.
     **/
    public void setZip(String zip) {
        this.zip = zip;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Customers))
            return false;
        
        Customers that = (Customers)o;

        if (firstName != null ? !firstName.equals(that.firstName) : that.firstName != null)
            return false;
        

        if (lastName != null ? !lastName.equals(that.lastName) : that.lastName != null)
            return false;
        

        if (emailAddress != null ? !emailAddress.equals(that.emailAddress) : that.emailAddress != null)
            return false;
        

        if (address1 != null ? !address1.equals(that.address1) : that.address1 != null)
            return false;
        

        if (address2 != null ? !address2.equals(that.address2) : that.address2 != null)
            return false;
        

        if (city != null ? !city.equals(that.city) : that.city != null)
            return false;
        

        if (state != null ? !state.equals(that.state) : that.state != null)
            return false;
        

        if (zip != null ? !zip.equals(that.zip) : that.zip != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = firstName != null ? firstName.hashCode() : 0;

        res = 31 * res + (lastName != null ? lastName.hashCode() : 0);

        res = 31 * res + (emailAddress != null ? emailAddress.hashCode() : 0);

        res = 31 * res + (address1 != null ? address1.hashCode() : 0);

        res = 31 * res + (address2 != null ? address2.hashCode() : 0);

        res = 31 * res + (city != null ? city.hashCode() : 0);

        res = 31 * res + (state != null ? state.hashCode() : 0);

        res = 31 * res + (zip != null ? zip.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Customers [" + 
            "firstName=" + firstName + ", " + 
            "lastName=" + lastName + ", " + 
            "emailAddress=" + emailAddress + ", " + 
            "address1=" + address1 + ", " + 
            "address2=" + address2 + ", " + 
            "city=" + city + ", " + 
            "state=" + state + ", " + 
            "zip=" + zip +
        "]";
    }
}