package com.pluralsight.duckair.model;

import java.io.Serializable;

/**
 * Fix definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class Fix implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for recordtype. */
    private String recordtype;

    /** Value for fixident. */
    private String fixident;

    /** Value for fixstatename. */
    private String fixstatename;

    /** Value for icaoregioncode. */
    private String icaoregioncode;

    /** Value for fixlatitude. */
    private String fixlatitude;

    /** Value for fixlongitude. */
    private String fixlongitude;

    /** Value for civilormilfix. */
    private String civilormilfix;

    /** Value for mlscomponentdata. */
    private String mlscomponentdata;

    /** Value for fixdescription. */
    private String fixdescription;

    /** Value for previousfixname. */
    private String previousfixname;

    /** Value for chart. */
    private String chart;

    /** Value for published. */
    private String published;

    /** Value for fixuse. */
    private String fixuse;

    /** Value for nasident. */
    private String nasident;

    /** Value for artcchigh. */
    private String artcchigh;

    /** Value for artcclow. */
    private String artcclow;

    /** Value for fixcountry. */
    private String fixcountry;

    /** Value for pitch. */
    private String pitch;

    /** Value for fieldCatch. */
    private String fieldCatch;

    /** Value for suaatcaa. */
    private String suaatcaa;

    /** Value for blank. */
    private String blank;

    /** Empty constructor. **/
    public Fix() {
        // No-op.
    }

    /** Full constructor. **/
    public Fix(String recordtype,
        String fixident,
        String fixstatename,
        String icaoregioncode,
        String fixlatitude,
        String fixlongitude,
        String civilormilfix,
        String mlscomponentdata,
        String fixdescription,
        String previousfixname,
        String chart,
        String published,
        String fixuse,
        String nasident,
        String artcchigh,
        String artcclow,
        String fixcountry,
        String pitch,
        String fieldCatch,
        String suaatcaa,
        String blank) {
        this.recordtype = recordtype;
        this.fixident = fixident;
        this.fixstatename = fixstatename;
        this.icaoregioncode = icaoregioncode;
        this.fixlatitude = fixlatitude;
        this.fixlongitude = fixlongitude;
        this.civilormilfix = civilormilfix;
        this.mlscomponentdata = mlscomponentdata;
        this.fixdescription = fixdescription;
        this.previousfixname = previousfixname;
        this.chart = chart;
        this.published = published;
        this.fixuse = fixuse;
        this.nasident = nasident;
        this.artcchigh = artcchigh;
        this.artcclow = artcclow;
        this.fixcountry = fixcountry;
        this.pitch = pitch;
        this.fieldCatch = fieldCatch;
        this.suaatcaa = suaatcaa;
        this.blank = blank;
    }

    /**
     * Gets recordtype
     * 
     * @return Value for recordtype.
     **/
    public String getRecordtype() {
        return recordtype;
    }

    /**
     * Sets recordtype
     * 
     * @param recordtype New value for recordtype.
     **/
    public void setRecordtype(String recordtype) {
        this.recordtype = recordtype;
    }

    /**
     * Gets fixident
     * 
     * @return Value for fixident.
     **/
    public String getFixident() {
        return fixident;
    }

    /**
     * Sets fixident
     * 
     * @param fixident New value for fixident.
     **/
    public void setFixident(String fixident) {
        this.fixident = fixident;
    }

    /**
     * Gets fixstatename
     * 
     * @return Value for fixstatename.
     **/
    public String getFixstatename() {
        return fixstatename;
    }

    /**
     * Sets fixstatename
     * 
     * @param fixstatename New value for fixstatename.
     **/
    public void setFixstatename(String fixstatename) {
        this.fixstatename = fixstatename;
    }

    /**
     * Gets icaoregioncode
     * 
     * @return Value for icaoregioncode.
     **/
    public String getIcaoregioncode() {
        return icaoregioncode;
    }

    /**
     * Sets icaoregioncode
     * 
     * @param icaoregioncode New value for icaoregioncode.
     **/
    public void setIcaoregioncode(String icaoregioncode) {
        this.icaoregioncode = icaoregioncode;
    }

    /**
     * Gets fixlatitude
     * 
     * @return Value for fixlatitude.
     **/
    public String getFixlatitude() {
        return fixlatitude;
    }

    /**
     * Sets fixlatitude
     * 
     * @param fixlatitude New value for fixlatitude.
     **/
    public void setFixlatitude(String fixlatitude) {
        this.fixlatitude = fixlatitude;
    }

    /**
     * Gets fixlongitude
     * 
     * @return Value for fixlongitude.
     **/
    public String getFixlongitude() {
        return fixlongitude;
    }

    /**
     * Sets fixlongitude
     * 
     * @param fixlongitude New value for fixlongitude.
     **/
    public void setFixlongitude(String fixlongitude) {
        this.fixlongitude = fixlongitude;
    }

    /**
     * Gets civilormilfix
     * 
     * @return Value for civilormilfix.
     **/
    public String getCivilormilfix() {
        return civilormilfix;
    }

    /**
     * Sets civilormilfix
     * 
     * @param civilormilfix New value for civilormilfix.
     **/
    public void setCivilormilfix(String civilormilfix) {
        this.civilormilfix = civilormilfix;
    }

    /**
     * Gets mlscomponentdata
     * 
     * @return Value for mlscomponentdata.
     **/
    public String getMlscomponentdata() {
        return mlscomponentdata;
    }

    /**
     * Sets mlscomponentdata
     * 
     * @param mlscomponentdata New value for mlscomponentdata.
     **/
    public void setMlscomponentdata(String mlscomponentdata) {
        this.mlscomponentdata = mlscomponentdata;
    }

    /**
     * Gets fixdescription
     * 
     * @return Value for fixdescription.
     **/
    public String getFixdescription() {
        return fixdescription;
    }

    /**
     * Sets fixdescription
     * 
     * @param fixdescription New value for fixdescription.
     **/
    public void setFixdescription(String fixdescription) {
        this.fixdescription = fixdescription;
    }

    /**
     * Gets previousfixname
     * 
     * @return Value for previousfixname.
     **/
    public String getPreviousfixname() {
        return previousfixname;
    }

    /**
     * Sets previousfixname
     * 
     * @param previousfixname New value for previousfixname.
     **/
    public void setPreviousfixname(String previousfixname) {
        this.previousfixname = previousfixname;
    }

    /**
     * Gets chart
     * 
     * @return Value for chart.
     **/
    public String getChart() {
        return chart;
    }

    /**
     * Sets chart
     * 
     * @param chart New value for chart.
     **/
    public void setChart(String chart) {
        this.chart = chart;
    }

    /**
     * Gets published
     * 
     * @return Value for published.
     **/
    public String getPublished() {
        return published;
    }

    /**
     * Sets published
     * 
     * @param published New value for published.
     **/
    public void setPublished(String published) {
        this.published = published;
    }

    /**
     * Gets fixuse
     * 
     * @return Value for fixuse.
     **/
    public String getFixuse() {
        return fixuse;
    }

    /**
     * Sets fixuse
     * 
     * @param fixuse New value for fixuse.
     **/
    public void setFixuse(String fixuse) {
        this.fixuse = fixuse;
    }

    /**
     * Gets nasident
     * 
     * @return Value for nasident.
     **/
    public String getNasident() {
        return nasident;
    }

    /**
     * Sets nasident
     * 
     * @param nasident New value for nasident.
     **/
    public void setNasident(String nasident) {
        this.nasident = nasident;
    }

    /**
     * Gets artcchigh
     * 
     * @return Value for artcchigh.
     **/
    public String getArtcchigh() {
        return artcchigh;
    }

    /**
     * Sets artcchigh
     * 
     * @param artcchigh New value for artcchigh.
     **/
    public void setArtcchigh(String artcchigh) {
        this.artcchigh = artcchigh;
    }

    /**
     * Gets artcclow
     * 
     * @return Value for artcclow.
     **/
    public String getArtcclow() {
        return artcclow;
    }

    /**
     * Sets artcclow
     * 
     * @param artcclow New value for artcclow.
     **/
    public void setArtcclow(String artcclow) {
        this.artcclow = artcclow;
    }

    /**
     * Gets fixcountry
     * 
     * @return Value for fixcountry.
     **/
    public String getFixcountry() {
        return fixcountry;
    }

    /**
     * Sets fixcountry
     * 
     * @param fixcountry New value for fixcountry.
     **/
    public void setFixcountry(String fixcountry) {
        this.fixcountry = fixcountry;
    }

    /**
     * Gets pitch
     * 
     * @return Value for pitch.
     **/
    public String getPitch() {
        return pitch;
    }

    /**
     * Sets pitch
     * 
     * @param pitch New value for pitch.
     **/
    public void setPitch(String pitch) {
        this.pitch = pitch;
    }

    /**
     * Gets fieldCatch
     * 
     * @return Value for fieldCatch.
     **/
    public String getFieldCatch() {
        return fieldCatch;
    }

    /**
     * Sets fieldCatch
     * 
     * @param fieldCatch New value for fieldCatch.
     **/
    public void setFieldCatch(String fieldCatch) {
        this.fieldCatch = fieldCatch;
    }

    /**
     * Gets suaatcaa
     * 
     * @return Value for suaatcaa.
     **/
    public String getSuaatcaa() {
        return suaatcaa;
    }

    /**
     * Sets suaatcaa
     * 
     * @param suaatcaa New value for suaatcaa.
     **/
    public void setSuaatcaa(String suaatcaa) {
        this.suaatcaa = suaatcaa;
    }

    /**
     * Gets blank
     * 
     * @return Value for blank.
     **/
    public String getBlank() {
        return blank;
    }

    /**
     * Sets blank
     * 
     * @param blank New value for blank.
     **/
    public void setBlank(String blank) {
        this.blank = blank;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Fix))
            return false;
        
        Fix that = (Fix)o;

        if (recordtype != null ? !recordtype.equals(that.recordtype) : that.recordtype != null)
            return false;
        

        if (fixident != null ? !fixident.equals(that.fixident) : that.fixident != null)
            return false;
        

        if (fixstatename != null ? !fixstatename.equals(that.fixstatename) : that.fixstatename != null)
            return false;
        

        if (icaoregioncode != null ? !icaoregioncode.equals(that.icaoregioncode) : that.icaoregioncode != null)
            return false;
        

        if (fixlatitude != null ? !fixlatitude.equals(that.fixlatitude) : that.fixlatitude != null)
            return false;
        

        if (fixlongitude != null ? !fixlongitude.equals(that.fixlongitude) : that.fixlongitude != null)
            return false;
        

        if (civilormilfix != null ? !civilormilfix.equals(that.civilormilfix) : that.civilormilfix != null)
            return false;
        

        if (mlscomponentdata != null ? !mlscomponentdata.equals(that.mlscomponentdata) : that.mlscomponentdata != null)
            return false;
        

        if (fixdescription != null ? !fixdescription.equals(that.fixdescription) : that.fixdescription != null)
            return false;
        

        if (previousfixname != null ? !previousfixname.equals(that.previousfixname) : that.previousfixname != null)
            return false;
        

        if (chart != null ? !chart.equals(that.chart) : that.chart != null)
            return false;
        

        if (published != null ? !published.equals(that.published) : that.published != null)
            return false;
        

        if (fixuse != null ? !fixuse.equals(that.fixuse) : that.fixuse != null)
            return false;
        

        if (nasident != null ? !nasident.equals(that.nasident) : that.nasident != null)
            return false;
        

        if (artcchigh != null ? !artcchigh.equals(that.artcchigh) : that.artcchigh != null)
            return false;
        

        if (artcclow != null ? !artcclow.equals(that.artcclow) : that.artcclow != null)
            return false;
        

        if (fixcountry != null ? !fixcountry.equals(that.fixcountry) : that.fixcountry != null)
            return false;
        

        if (pitch != null ? !pitch.equals(that.pitch) : that.pitch != null)
            return false;
        

        if (fieldCatch != null ? !fieldCatch.equals(that.fieldCatch) : that.fieldCatch != null)
            return false;
        

        if (suaatcaa != null ? !suaatcaa.equals(that.suaatcaa) : that.suaatcaa != null)
            return false;
        

        if (blank != null ? !blank.equals(that.blank) : that.blank != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = recordtype != null ? recordtype.hashCode() : 0;

        res = 31 * res + (fixident != null ? fixident.hashCode() : 0);

        res = 31 * res + (fixstatename != null ? fixstatename.hashCode() : 0);

        res = 31 * res + (icaoregioncode != null ? icaoregioncode.hashCode() : 0);

        res = 31 * res + (fixlatitude != null ? fixlatitude.hashCode() : 0);

        res = 31 * res + (fixlongitude != null ? fixlongitude.hashCode() : 0);

        res = 31 * res + (civilormilfix != null ? civilormilfix.hashCode() : 0);

        res = 31 * res + (mlscomponentdata != null ? mlscomponentdata.hashCode() : 0);

        res = 31 * res + (fixdescription != null ? fixdescription.hashCode() : 0);

        res = 31 * res + (previousfixname != null ? previousfixname.hashCode() : 0);

        res = 31 * res + (chart != null ? chart.hashCode() : 0);

        res = 31 * res + (published != null ? published.hashCode() : 0);

        res = 31 * res + (fixuse != null ? fixuse.hashCode() : 0);

        res = 31 * res + (nasident != null ? nasident.hashCode() : 0);

        res = 31 * res + (artcchigh != null ? artcchigh.hashCode() : 0);

        res = 31 * res + (artcclow != null ? artcclow.hashCode() : 0);

        res = 31 * res + (fixcountry != null ? fixcountry.hashCode() : 0);

        res = 31 * res + (pitch != null ? pitch.hashCode() : 0);

        res = 31 * res + (fieldCatch != null ? fieldCatch.hashCode() : 0);

        res = 31 * res + (suaatcaa != null ? suaatcaa.hashCode() : 0);

        res = 31 * res + (blank != null ? blank.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Fix [" + 
            "recordtype=" + recordtype + ", " + 
            "fixident=" + fixident + ", " + 
            "fixstatename=" + fixstatename + ", " + 
            "icaoregioncode=" + icaoregioncode + ", " + 
            "fixlatitude=" + fixlatitude + ", " + 
            "fixlongitude=" + fixlongitude + ", " + 
            "civilormilfix=" + civilormilfix + ", " + 
            "mlscomponentdata=" + mlscomponentdata + ", " + 
            "fixdescription=" + fixdescription + ", " + 
            "previousfixname=" + previousfixname + ", " + 
            "chart=" + chart + ", " + 
            "published=" + published + ", " + 
            "fixuse=" + fixuse + ", " + 
            "nasident=" + nasident + ", " + 
            "artcchigh=" + artcchigh + ", " + 
            "artcclow=" + artcclow + ", " + 
            "fixcountry=" + fixcountry + ", " + 
            "pitch=" + pitch + ", " + 
            "fieldCatch=" + fieldCatch + ", " + 
            "suaatcaa=" + suaatcaa + ", " + 
            "blank=" + blank +
        "]";
    }
}