package com.pluralsight.duckair.model;

import java.io.Serializable;

/**
 * Fleet definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class Fleet implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for aircraftId. */
    private Integer aircraftId;

    /** Value for airframeHours. */
    private Integer airframeHours;

    /** Value for tailNumber. */
    private String tailNumber;

    /** Value for capacity. */
    private String capacity;

    /** Empty constructor. **/
    public Fleet() {
        // No-op.
    }

    /** Full constructor. **/
    public Fleet(Integer aircraftId,
        Integer airframeHours,
        String tailNumber,
        String capacity) {
        this.aircraftId = aircraftId;
        this.airframeHours = airframeHours;
        this.tailNumber = tailNumber;
        this.capacity = capacity;
    }

    /**
     * Gets aircraftId
     * 
     * @return Value for aircraftId.
     **/
    public Integer getAircraftId() {
        return aircraftId;
    }

    /**
     * Sets aircraftId
     * 
     * @param aircraftId New value for aircraftId.
     **/
    public void setAircraftId(Integer aircraftId) {
        this.aircraftId = aircraftId;
    }

    /**
     * Gets airframeHours
     * 
     * @return Value for airframeHours.
     **/
    public Integer getAirframeHours() {
        return airframeHours;
    }

    /**
     * Sets airframeHours
     * 
     * @param airframeHours New value for airframeHours.
     **/
    public void setAirframeHours(Integer airframeHours) {
        this.airframeHours = airframeHours;
    }

    /**
     * Gets tailNumber
     * 
     * @return Value for tailNumber.
     **/
    public String getTailNumber() {
        return tailNumber;
    }

    /**
     * Sets tailNumber
     * 
     * @param tailNumber New value for tailNumber.
     **/
    public void setTailNumber(String tailNumber) {
        this.tailNumber = tailNumber;
    }

    /**
     * Gets capacity
     * 
     * @return Value for capacity.
     **/
    public String getCapacity() {
        return capacity;
    }

    /**
     * Sets capacity
     * 
     * @param capacity New value for capacity.
     **/
    public void setCapacity(String capacity) {
        this.capacity = capacity;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Fleet))
            return false;
        
        Fleet that = (Fleet)o;

        if (aircraftId != null ? !aircraftId.equals(that.aircraftId) : that.aircraftId != null)
            return false;
        

        if (airframeHours != null ? !airframeHours.equals(that.airframeHours) : that.airframeHours != null)
            return false;
        

        if (tailNumber != null ? !tailNumber.equals(that.tailNumber) : that.tailNumber != null)
            return false;
        

        if (capacity != null ? !capacity.equals(that.capacity) : that.capacity != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = aircraftId != null ? aircraftId.hashCode() : 0;

        res = 31 * res + (airframeHours != null ? airframeHours.hashCode() : 0);

        res = 31 * res + (tailNumber != null ? tailNumber.hashCode() : 0);

        res = 31 * res + (capacity != null ? capacity.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Fleet [" + 
            "aircraftId=" + aircraftId + ", " + 
            "airframeHours=" + airframeHours + ", " + 
            "tailNumber=" + tailNumber + ", " + 
            "capacity=" + capacity +
        "]";
    }
}