package com.pluralsight.duckair.model;

import java.io.Serializable;

/**
 * FlightPlans definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class FlightPlans implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for flightNumber. */
    private String flightNumber;

    /** Value for fromAirportIcao. */
    private String fromAirportIcao;

    /** Value for toAirportIcao. */
    private String toAirportIcao;

    /** Value for distance. */
    private String distance;

    /** Value for filedAltitude. */
    private String filedAltitude;

    /** Value for filedAirspeed. */
    private String filedAirspeed;

    /** Value for fleetId. */
    private String fleetId;

    /** Value for estimatedMinutesEnroute. */
    private Integer estimatedMinutesEnroute;

    /** Value for timeAway. */
    private String timeAway;

    /** Value for flightStatus. */
    private String flightStatus;

    /** Empty constructor. **/
    public FlightPlans() {
        // No-op.
    }

    /** Full constructor. **/
    public FlightPlans(String flightNumber,
        String fromAirportIcao,
        String toAirportIcao,
        String distance,
        String filedAltitude,
        String filedAirspeed,
        String fleetId,
        Integer estimatedMinutesEnroute,
        String timeAway,
        String flightStatus) {
        this.flightNumber = flightNumber;
        this.fromAirportIcao = fromAirportIcao;
        this.toAirportIcao = toAirportIcao;
        this.distance = distance;
        this.filedAltitude = filedAltitude;
        this.filedAirspeed = filedAirspeed;
        this.fleetId = fleetId;
        this.estimatedMinutesEnroute = estimatedMinutesEnroute;
        this.timeAway = timeAway;
        this.flightStatus = flightStatus;
    }

    /**
     * Gets flightNumber
     * 
     * @return Value for flightNumber.
     **/
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets flightNumber
     * 
     * @param flightNumber New value for flightNumber.
     **/
    public void setFlightNumber(String flightNumber) {
        this.flightNumber = flightNumber;
    }

    /**
     * Gets fromAirportIcao
     * 
     * @return Value for fromAirportIcao.
     **/
    public String getFromAirportIcao() {
        return fromAirportIcao;
    }

    /**
     * Sets fromAirportIcao
     * 
     * @param fromAirportIcao New value for fromAirportIcao.
     **/
    public void setFromAirportIcao(String fromAirportIcao) {
        this.fromAirportIcao = fromAirportIcao;
    }

    /**
     * Gets toAirportIcao
     * 
     * @return Value for toAirportIcao.
     **/
    public String getToAirportIcao() {
        return toAirportIcao;
    }

    /**
     * Sets toAirportIcao
     * 
     * @param toAirportIcao New value for toAirportIcao.
     **/
    public void setToAirportIcao(String toAirportIcao) {
        this.toAirportIcao = toAirportIcao;
    }

    /**
     * Gets distance
     * 
     * @return Value for distance.
     **/
    public String getDistance() {
        return distance;
    }

    /**
     * Sets distance
     * 
     * @param distance New value for distance.
     **/
    public void setDistance(String distance) {
        this.distance = distance;
    }

    /**
     * Gets filedAltitude
     * 
     * @return Value for filedAltitude.
     **/
    public String getFiledAltitude() {
        return filedAltitude;
    }

    /**
     * Sets filedAltitude
     * 
     * @param filedAltitude New value for filedAltitude.
     **/
    public void setFiledAltitude(String filedAltitude) {
        this.filedAltitude = filedAltitude;
    }

    /**
     * Gets filedAirspeed
     * 
     * @return Value for filedAirspeed.
     **/
    public String getFiledAirspeed() {
        return filedAirspeed;
    }

    /**
     * Sets filedAirspeed
     * 
     * @param filedAirspeed New value for filedAirspeed.
     **/
    public void setFiledAirspeed(String filedAirspeed) {
        this.filedAirspeed = filedAirspeed;
    }

    /**
     * Gets fleetId
     * 
     * @return Value for fleetId.
     **/
    public String getFleetId() {
        return fleetId;
    }

    /**
     * Sets fleetId
     * 
     * @param fleetId New value for fleetId.
     **/
    public void setFleetId(String fleetId) {
        this.fleetId = fleetId;
    }

    /**
     * Gets estimatedMinutesEnroute
     * 
     * @return Value for estimatedMinutesEnroute.
     **/
    public Integer getEstimatedMinutesEnroute() {
        return estimatedMinutesEnroute;
    }

    /**
     * Sets estimatedMinutesEnroute
     * 
     * @param estimatedMinutesEnroute New value for estimatedMinutesEnroute.
     **/
    public void setEstimatedMinutesEnroute(Integer estimatedMinutesEnroute) {
        this.estimatedMinutesEnroute = estimatedMinutesEnroute;
    }

    /**
     * Gets timeAway
     * 
     * @return Value for timeAway.
     **/
    public String getTimeAway() {
        return timeAway;
    }

    /**
     * Sets timeAway
     * 
     * @param timeAway New value for timeAway.
     **/
    public void setTimeAway(String timeAway) {
        this.timeAway = timeAway;
    }

    /**
     * Gets flightStatus
     * 
     * @return Value for flightStatus.
     **/
    public String getFlightStatus() {
        return flightStatus;
    }

    /**
     * Sets flightStatus
     * 
     * @param flightStatus New value for flightStatus.
     **/
    public void setFlightStatus(String flightStatus) {
        this.flightStatus = flightStatus;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof FlightPlans))
            return false;
        
        FlightPlans that = (FlightPlans)o;

        if (flightNumber != null ? !flightNumber.equals(that.flightNumber) : that.flightNumber != null)
            return false;
        

        if (fromAirportIcao != null ? !fromAirportIcao.equals(that.fromAirportIcao) : that.fromAirportIcao != null)
            return false;
        

        if (toAirportIcao != null ? !toAirportIcao.equals(that.toAirportIcao) : that.toAirportIcao != null)
            return false;
        

        if (distance != null ? !distance.equals(that.distance) : that.distance != null)
            return false;
        

        if (filedAltitude != null ? !filedAltitude.equals(that.filedAltitude) : that.filedAltitude != null)
            return false;
        

        if (filedAirspeed != null ? !filedAirspeed.equals(that.filedAirspeed) : that.filedAirspeed != null)
            return false;
        

        if (fleetId != null ? !fleetId.equals(that.fleetId) : that.fleetId != null)
            return false;
        

        if (estimatedMinutesEnroute != null ? !estimatedMinutesEnroute.equals(that.estimatedMinutesEnroute) : that.estimatedMinutesEnroute != null)
            return false;
        

        if (timeAway != null ? !timeAway.equals(that.timeAway) : that.timeAway != null)
            return false;
        

        if (flightStatus != null ? !flightStatus.equals(that.flightStatus) : that.flightStatus != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = flightNumber != null ? flightNumber.hashCode() : 0;

        res = 31 * res + (fromAirportIcao != null ? fromAirportIcao.hashCode() : 0);

        res = 31 * res + (toAirportIcao != null ? toAirportIcao.hashCode() : 0);

        res = 31 * res + (distance != null ? distance.hashCode() : 0);

        res = 31 * res + (filedAltitude != null ? filedAltitude.hashCode() : 0);

        res = 31 * res + (filedAirspeed != null ? filedAirspeed.hashCode() : 0);

        res = 31 * res + (fleetId != null ? fleetId.hashCode() : 0);

        res = 31 * res + (estimatedMinutesEnroute != null ? estimatedMinutesEnroute.hashCode() : 0);

        res = 31 * res + (timeAway != null ? timeAway.hashCode() : 0);

        res = 31 * res + (flightStatus != null ? flightStatus.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "FlightPlans [" + 
            "flightNumber=" + flightNumber + ", " + 
            "fromAirportIcao=" + fromAirportIcao + ", " + 
            "toAirportIcao=" + toAirportIcao + ", " + 
            "distance=" + distance + ", " + 
            "filedAltitude=" + filedAltitude + ", " + 
            "filedAirspeed=" + filedAirspeed + ", " + 
            "fleetId=" + fleetId + ", " + 
            "estimatedMinutesEnroute=" + estimatedMinutesEnroute + ", " + 
            "timeAway=" + timeAway + ", " + 
            "flightStatus=" + flightStatus +
        "]";
    }
}