package com.pluralsight.duckair.model;

import java.io.Serializable;
import java.sql.Date;

/**
 * FrequentFlyer definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class FrequentFlyer implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for customerId. */
    private String customerId;

    /** Value for account. */
    private String account;

    /** Value for memberSince. */
    private Date memberSince;

    /** Value for total. */
    private Integer total;

    /** Value for used. */
    private Integer used;

    /** Value for balance. */
    private String balance;

    /** Value for level. */
    private String level;

    /** Empty constructor. **/
    public FrequentFlyer() {
        // No-op.
    }

    /** Full constructor. **/
    public FrequentFlyer(String customerId,
        String account,
        Date memberSince,
        Integer total,
        Integer used,
        String balance,
        String level) {
        this.customerId = customerId;
        this.account = account;
        this.memberSince = memberSince;
        this.total = total;
        this.used = used;
        this.balance = balance;
        this.level = level;
    }

    /**
     * Gets customerId
     * 
     * @return Value for customerId.
     **/
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets customerId
     * 
     * @param customerId New value for customerId.
     **/
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * Gets account
     * 
     * @return Value for account.
     **/
    public String getAccount() {
        return account;
    }

    /**
     * Sets account
     * 
     * @param account New value for account.
     **/
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * Gets memberSince
     * 
     * @return Value for memberSince.
     **/
    public Date getMemberSince() {
        return memberSince;
    }

    /**
     * Sets memberSince
     * 
     * @param memberSince New value for memberSince.
     **/
    public void setMemberSince(Date memberSince) {
        this.memberSince = memberSince;
    }

    /**
     * Gets total
     * 
     * @return Value for total.
     **/
    public Integer getTotal() {
        return total;
    }

    /**
     * Sets total
     * 
     * @param total New value for total.
     **/
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * Gets used
     * 
     * @return Value for used.
     **/
    public Integer getUsed() {
        return used;
    }

    /**
     * Sets used
     * 
     * @param used New value for used.
     **/
    public void setUsed(Integer used) {
        this.used = used;
    }

    /**
     * Gets balance
     * 
     * @return Value for balance.
     **/
    public String getBalance() {
        return balance;
    }

    /**
     * Sets balance
     * 
     * @param balance New value for balance.
     **/
    public void setBalance(String balance) {
        this.balance = balance;
    }

    /**
     * Gets level
     * 
     * @return Value for level.
     **/
    public String getLevel() {
        return level;
    }

    /**
     * Sets level
     * 
     * @param level New value for level.
     **/
    public void setLevel(String level) {
        this.level = level;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof FrequentFlyer))
            return false;
        
        FrequentFlyer that = (FrequentFlyer)o;

        if (customerId != null ? !customerId.equals(that.customerId) : that.customerId != null)
            return false;
        

        if (account != null ? !account.equals(that.account) : that.account != null)
            return false;
        

        if (memberSince != null ? !memberSince.equals(that.memberSince) : that.memberSince != null)
            return false;
        

        if (total != null ? !total.equals(that.total) : that.total != null)
            return false;
        

        if (used != null ? !used.equals(that.used) : that.used != null)
            return false;
        

        if (balance != null ? !balance.equals(that.balance) : that.balance != null)
            return false;
        

        if (level != null ? !level.equals(that.level) : that.level != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = customerId != null ? customerId.hashCode() : 0;

        res = 31 * res + (account != null ? account.hashCode() : 0);

        res = 31 * res + (memberSince != null ? memberSince.hashCode() : 0);

        res = 31 * res + (total != null ? total.hashCode() : 0);

        res = 31 * res + (used != null ? used.hashCode() : 0);

        res = 31 * res + (balance != null ? balance.hashCode() : 0);

        res = 31 * res + (level != null ? level.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "FrequentFlyer [" + 
            "customerId=" + customerId + ", " + 
            "account=" + account + ", " + 
            "memberSince=" + memberSince + ", " + 
            "total=" + total + ", " + 
            "used=" + used + ", " + 
            "balance=" + balance + ", " + 
            "level=" + level +
        "]";
    }
}