package com.pluralsight.duckair.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

/**
 * Navaid definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class Navaid implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for recordtype. */
    private String recordtype;

    /** Value for facilityident. */
    private String facilityident;

    /** Value for facilitytype. */
    private String facilitytype;

    /** Value for navaidident. */
    private String navaidident;

    /** Value for effectivedate. */
    private Date effectivedate;

    /** Value for navaidname. */
    private String navaidname;

    /** Value for city. */
    private String city;

    /** Value for state. */
    private String state;

    /** Value for stateabbr. */
    private String stateabbr;

    /** Value for faaregion. */
    private String faaregion;

    /** Value for country. */
    private String country;

    /** Value for countryabbr. */
    private String countryabbr;

    /** Value for ownername. */
    private String ownername;

    /** Value for operatorname. */
    private String operatorname;

    /** Value for commonusage. */
    private String commonusage;

    /** Value for publicuse. */
    private String publicuse;

    /** Value for operationalhours. */
    private String operationalhours;

    /** Value for identhigh. */
    private String identhigh;

    /** Value for artcchigh. */
    private String artcchigh;

    /** Value for identlow. */
    private String identlow;

    /** Value for artcclow. */
    private String artcclow;

    /** Value for latitude. */
    private String latitude;

    /** Value for latitudes. */
    private String latitudes;

    /** Value for longitude. */
    private String longitude;

    /** Value for longitudes. */
    private String longitudes;

    /** Value for latlongaccuracy. */
    private String latlongaccuracy;

    /** Value for tacanlatitude. */
    private String tacanlatitude;

    /** Value for tacanlatitudes. */
    private String tacanlatitudes;

    /** Value for tacanlongitude. */
    private String tacanlongitude;

    /** Value for tacanlongitudes. */
    private String tacanlongitudes;

    /** Value for elevation. */
    private String elevation;

    /** Value for magneticvariation. */
    private String magneticvariation;

    /** Value for magneticvariationepoch. */
    private String magneticvariationepoch;

    /** Value for voice. */
    private String voice;

    /** Value for poweroutput. */
    private String poweroutput;

    /** Value for voiceident. */
    private String voiceident;

    /** Value for monitoringcategory. */
    private String monitoringcategory;

    /** Value for radiocallname. */
    private String radiocallname;

    /** Value for tacanchannel. */
    private String tacanchannel;

    /** Value for frequency. */
    private String frequency;

    /** Value for morsecodeident. */
    private String morsecodeident;

    /** Value for fanmarkertype. */
    private String fanmarkertype;

    /** Value for truebearing. */
    private String truebearing;

    /** Value for protectedfreqaltitude. */
    private String protectedfreqaltitude;

    /** Value for highalthaslowradio. */
    private String highalthaslowradio;

    /** Value for navaidzmarker. */
    private String navaidzmarker;

    /** Value for weatherbroadcasthours. */
    private String weatherbroadcasthours;

    /** Value for weatherbroadcastphone. */
    private String weatherbroadcastphone;

    /** Value for controllingfssident. */
    private String controllingfssident;

    /** Value for controllingfssname. */
    private String controllingfssname;

    /** Value for fsshours. */
    private String fsshours;

    /** Value for notamaccountabilitycode. */
    private String notamaccountabilitycode;

    /** Value for quadidentandrangelegbearing. */
    private String quadidentandrangelegbearing;

    /** Value for status. */
    private String status;

    /** Value for pitch. */
    private String pitch;

    /** Value for fieldCatch. */
    private String fieldCatch;

    /** Value for suaatcaa. */
    private String suaatcaa;

    /** Value for restriction. */
    private String restriction;

    /** Value for hiwas. */
    private String hiwas;

    /** Value for twebrestriction. */
    private String twebrestriction;

    /** Value for longituded. */
    private BigDecimal longituded;

    /** Value for latituded. */
    private BigDecimal latituded;

    /** Empty constructor. **/
    public Navaid() {
        // No-op.
    }

    /** Full constructor. **/
    public Navaid(String recordtype,
        String facilityident,
        String facilitytype,
        String navaidident,
        Date effectivedate,
        String navaidname,
        String city,
        String state,
        String stateabbr,
        String faaregion,
        String country,
        String countryabbr,
        String ownername,
        String operatorname,
        String commonusage,
        String publicuse,
        String operationalhours,
        String identhigh,
        String artcchigh,
        String identlow,
        String artcclow,
        String latitude,
        String latitudes,
        String longitude,
        String longitudes,
        String latlongaccuracy,
        String tacanlatitude,
        String tacanlatitudes,
        String tacanlongitude,
        String tacanlongitudes,
        String elevation,
        String magneticvariation,
        String magneticvariationepoch,
        String voice,
        String poweroutput,
        String voiceident,
        String monitoringcategory,
        String radiocallname,
        String tacanchannel,
        String frequency,
        String morsecodeident,
        String fanmarkertype,
        String truebearing,
        String protectedfreqaltitude,
        String highalthaslowradio,
        String navaidzmarker,
        String weatherbroadcasthours,
        String weatherbroadcastphone,
        String controllingfssident,
        String controllingfssname,
        String fsshours,
        String notamaccountabilitycode,
        String quadidentandrangelegbearing,
        String status,
        String pitch,
        String fieldCatch,
        String suaatcaa,
        String restriction,
        String hiwas,
        String twebrestriction,
        BigDecimal longituded,
        BigDecimal latituded) {
        this.recordtype = recordtype;
        this.facilityident = facilityident;
        this.facilitytype = facilitytype;
        this.navaidident = navaidident;
        this.effectivedate = effectivedate;
        this.navaidname = navaidname;
        this.city = city;
        this.state = state;
        this.stateabbr = stateabbr;
        this.faaregion = faaregion;
        this.country = country;
        this.countryabbr = countryabbr;
        this.ownername = ownername;
        this.operatorname = operatorname;
        this.commonusage = commonusage;
        this.publicuse = publicuse;
        this.operationalhours = operationalhours;
        this.identhigh = identhigh;
        this.artcchigh = artcchigh;
        this.identlow = identlow;
        this.artcclow = artcclow;
        this.latitude = latitude;
        this.latitudes = latitudes;
        this.longitude = longitude;
        this.longitudes = longitudes;
        this.latlongaccuracy = latlongaccuracy;
        this.tacanlatitude = tacanlatitude;
        this.tacanlatitudes = tacanlatitudes;
        this.tacanlongitude = tacanlongitude;
        this.tacanlongitudes = tacanlongitudes;
        this.elevation = elevation;
        this.magneticvariation = magneticvariation;
        this.magneticvariationepoch = magneticvariationepoch;
        this.voice = voice;
        this.poweroutput = poweroutput;
        this.voiceident = voiceident;
        this.monitoringcategory = monitoringcategory;
        this.radiocallname = radiocallname;
        this.tacanchannel = tacanchannel;
        this.frequency = frequency;
        this.morsecodeident = morsecodeident;
        this.fanmarkertype = fanmarkertype;
        this.truebearing = truebearing;
        this.protectedfreqaltitude = protectedfreqaltitude;
        this.highalthaslowradio = highalthaslowradio;
        this.navaidzmarker = navaidzmarker;
        this.weatherbroadcasthours = weatherbroadcasthours;
        this.weatherbroadcastphone = weatherbroadcastphone;
        this.controllingfssident = controllingfssident;
        this.controllingfssname = controllingfssname;
        this.fsshours = fsshours;
        this.notamaccountabilitycode = notamaccountabilitycode;
        this.quadidentandrangelegbearing = quadidentandrangelegbearing;
        this.status = status;
        this.pitch = pitch;
        this.fieldCatch = fieldCatch;
        this.suaatcaa = suaatcaa;
        this.restriction = restriction;
        this.hiwas = hiwas;
        this.twebrestriction = twebrestriction;
        this.longituded = longituded;
        this.latituded = latituded;
    }

    /**
     * Gets recordtype
     * 
     * @return Value for recordtype.
     **/
    public String getRecordtype() {
        return recordtype;
    }

    /**
     * Sets recordtype
     * 
     * @param recordtype New value for recordtype.
     **/
    public void setRecordtype(String recordtype) {
        this.recordtype = recordtype;
    }

    /**
     * Gets facilityident
     * 
     * @return Value for facilityident.
     **/
    public String getFacilityident() {
        return facilityident;
    }

    /**
     * Sets facilityident
     * 
     * @param facilityident New value for facilityident.
     **/
    public void setFacilityident(String facilityident) {
        this.facilityident = facilityident;
    }

    /**
     * Gets facilitytype
     * 
     * @return Value for facilitytype.
     **/
    public String getFacilitytype() {
        return facilitytype;
    }

    /**
     * Sets facilitytype
     * 
     * @param facilitytype New value for facilitytype.
     **/
    public void setFacilitytype(String facilitytype) {
        this.facilitytype = facilitytype;
    }

    /**
     * Gets navaidident
     * 
     * @return Value for navaidident.
     **/
    public String getNavaidident() {
        return navaidident;
    }

    /**
     * Sets navaidident
     * 
     * @param navaidident New value for navaidident.
     **/
    public void setNavaidident(String navaidident) {
        this.navaidident = navaidident;
    }

    /**
     * Gets effectivedate
     * 
     * @return Value for effectivedate.
     **/
    public Date getEffectivedate() {
        return effectivedate;
    }

    /**
     * Sets effectivedate
     * 
     * @param effectivedate New value for effectivedate.
     **/
    public void setEffectivedate(Date effectivedate) {
        this.effectivedate = effectivedate;
    }

    /**
     * Gets navaidname
     * 
     * @return Value for navaidname.
     **/
    public String getNavaidname() {
        return navaidname;
    }

    /**
     * Sets navaidname
     * 
     * @param navaidname New value for navaidname.
     **/
    public void setNavaidname(String navaidname) {
        this.navaidname = navaidname;
    }

    /**
     * Gets city
     * 
     * @return Value for city.
     **/
    public String getCity() {
        return city;
    }

    /**
     * Sets city
     * 
     * @param city New value for city.
     **/
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Gets state
     * 
     * @return Value for state.
     **/
    public String getState() {
        return state;
    }

    /**
     * Sets state
     * 
     * @param state New value for state.
     **/
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Gets stateabbr
     * 
     * @return Value for stateabbr.
     **/
    public String getStateabbr() {
        return stateabbr;
    }

    /**
     * Sets stateabbr
     * 
     * @param stateabbr New value for stateabbr.
     **/
    public void setStateabbr(String stateabbr) {
        this.stateabbr = stateabbr;
    }

    /**
     * Gets faaregion
     * 
     * @return Value for faaregion.
     **/
    public String getFaaregion() {
        return faaregion;
    }

    /**
     * Sets faaregion
     * 
     * @param faaregion New value for faaregion.
     **/
    public void setFaaregion(String faaregion) {
        this.faaregion = faaregion;
    }

    /**
     * Gets country
     * 
     * @return Value for country.
     **/
    public String getCountry() {
        return country;
    }

    /**
     * Sets country
     * 
     * @param country New value for country.
     **/
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Gets countryabbr
     * 
     * @return Value for countryabbr.
     **/
    public String getCountryabbr() {
        return countryabbr;
    }

    /**
     * Sets countryabbr
     * 
     * @param countryabbr New value for countryabbr.
     **/
    public void setCountryabbr(String countryabbr) {
        this.countryabbr = countryabbr;
    }

    /**
     * Gets ownername
     * 
     * @return Value for ownername.
     **/
    public String getOwnername() {
        return ownername;
    }

    /**
     * Sets ownername
     * 
     * @param ownername New value for ownername.
     **/
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }

    /**
     * Gets operatorname
     * 
     * @return Value for operatorname.
     **/
    public String getOperatorname() {
        return operatorname;
    }

    /**
     * Sets operatorname
     * 
     * @param operatorname New value for operatorname.
     **/
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname;
    }

    /**
     * Gets commonusage
     * 
     * @return Value for commonusage.
     **/
    public String getCommonusage() {
        return commonusage;
    }

    /**
     * Sets commonusage
     * 
     * @param commonusage New value for commonusage.
     **/
    public void setCommonusage(String commonusage) {
        this.commonusage = commonusage;
    }

    /**
     * Gets publicuse
     * 
     * @return Value for publicuse.
     **/
    public String getPublicuse() {
        return publicuse;
    }

    /**
     * Sets publicuse
     * 
     * @param publicuse New value for publicuse.
     **/
    public void setPublicuse(String publicuse) {
        this.publicuse = publicuse;
    }

    /**
     * Gets operationalhours
     * 
     * @return Value for operationalhours.
     **/
    public String getOperationalhours() {
        return operationalhours;
    }

    /**
     * Sets operationalhours
     * 
     * @param operationalhours New value for operationalhours.
     **/
    public void setOperationalhours(String operationalhours) {
        this.operationalhours = operationalhours;
    }

    /**
     * Gets identhigh
     * 
     * @return Value for identhigh.
     **/
    public String getIdenthigh() {
        return identhigh;
    }

    /**
     * Sets identhigh
     * 
     * @param identhigh New value for identhigh.
     **/
    public void setIdenthigh(String identhigh) {
        this.identhigh = identhigh;
    }

    /**
     * Gets artcchigh
     * 
     * @return Value for artcchigh.
     **/
    public String getArtcchigh() {
        return artcchigh;
    }

    /**
     * Sets artcchigh
     * 
     * @param artcchigh New value for artcchigh.
     **/
    public void setArtcchigh(String artcchigh) {
        this.artcchigh = artcchigh;
    }

    /**
     * Gets identlow
     * 
     * @return Value for identlow.
     **/
    public String getIdentlow() {
        return identlow;
    }

    /**
     * Sets identlow
     * 
     * @param identlow New value for identlow.
     **/
    public void setIdentlow(String identlow) {
        this.identlow = identlow;
    }

    /**
     * Gets artcclow
     * 
     * @return Value for artcclow.
     **/
    public String getArtcclow() {
        return artcclow;
    }

    /**
     * Sets artcclow
     * 
     * @param artcclow New value for artcclow.
     **/
    public void setArtcclow(String artcclow) {
        this.artcclow = artcclow;
    }

    /**
     * Gets latitude
     * 
     * @return Value for latitude.
     **/
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets latitude
     * 
     * @param latitude New value for latitude.
     **/
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * Gets latitudes
     * 
     * @return Value for latitudes.
     **/
    public String getLatitudes() {
        return latitudes;
    }

    /**
     * Sets latitudes
     * 
     * @param latitudes New value for latitudes.
     **/
    public void setLatitudes(String latitudes) {
        this.latitudes = latitudes;
    }

    /**
     * Gets longitude
     * 
     * @return Value for longitude.
     **/
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets longitude
     * 
     * @param longitude New value for longitude.
     **/
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * Gets longitudes
     * 
     * @return Value for longitudes.
     **/
    public String getLongitudes() {
        return longitudes;
    }

    /**
     * Sets longitudes
     * 
     * @param longitudes New value for longitudes.
     **/
    public void setLongitudes(String longitudes) {
        this.longitudes = longitudes;
    }

    /**
     * Gets latlongaccuracy
     * 
     * @return Value for latlongaccuracy.
     **/
    public String getLatlongaccuracy() {
        return latlongaccuracy;
    }

    /**
     * Sets latlongaccuracy
     * 
     * @param latlongaccuracy New value for latlongaccuracy.
     **/
    public void setLatlongaccuracy(String latlongaccuracy) {
        this.latlongaccuracy = latlongaccuracy;
    }

    /**
     * Gets tacanlatitude
     * 
     * @return Value for tacanlatitude.
     **/
    public String getTacanlatitude() {
        return tacanlatitude;
    }

    /**
     * Sets tacanlatitude
     * 
     * @param tacanlatitude New value for tacanlatitude.
     **/
    public void setTacanlatitude(String tacanlatitude) {
        this.tacanlatitude = tacanlatitude;
    }

    /**
     * Gets tacanlatitudes
     * 
     * @return Value for tacanlatitudes.
     **/
    public String getTacanlatitudes() {
        return tacanlatitudes;
    }

    /**
     * Sets tacanlatitudes
     * 
     * @param tacanlatitudes New value for tacanlatitudes.
     **/
    public void setTacanlatitudes(String tacanlatitudes) {
        this.tacanlatitudes = tacanlatitudes;
    }

    /**
     * Gets tacanlongitude
     * 
     * @return Value for tacanlongitude.
     **/
    public String getTacanlongitude() {
        return tacanlongitude;
    }

    /**
     * Sets tacanlongitude
     * 
     * @param tacanlongitude New value for tacanlongitude.
     **/
    public void setTacanlongitude(String tacanlongitude) {
        this.tacanlongitude = tacanlongitude;
    }

    /**
     * Gets tacanlongitudes
     * 
     * @return Value for tacanlongitudes.
     **/
    public String getTacanlongitudes() {
        return tacanlongitudes;
    }

    /**
     * Sets tacanlongitudes
     * 
     * @param tacanlongitudes New value for tacanlongitudes.
     **/
    public void setTacanlongitudes(String tacanlongitudes) {
        this.tacanlongitudes = tacanlongitudes;
    }

    /**
     * Gets elevation
     * 
     * @return Value for elevation.
     **/
    public String getElevation() {
        return elevation;
    }

    /**
     * Sets elevation
     * 
     * @param elevation New value for elevation.
     **/
    public void setElevation(String elevation) {
        this.elevation = elevation;
    }

    /**
     * Gets magneticvariation
     * 
     * @return Value for magneticvariation.
     **/
    public String getMagneticvariation() {
        return magneticvariation;
    }

    /**
     * Sets magneticvariation
     * 
     * @param magneticvariation New value for magneticvariation.
     **/
    public void setMagneticvariation(String magneticvariation) {
        this.magneticvariation = magneticvariation;
    }

    /**
     * Gets magneticvariationepoch
     * 
     * @return Value for magneticvariationepoch.
     **/
    public String getMagneticvariationepoch() {
        return magneticvariationepoch;
    }

    /**
     * Sets magneticvariationepoch
     * 
     * @param magneticvariationepoch New value for magneticvariationepoch.
     **/
    public void setMagneticvariationepoch(String magneticvariationepoch) {
        this.magneticvariationepoch = magneticvariationepoch;
    }

    /**
     * Gets voice
     * 
     * @return Value for voice.
     **/
    public String getVoice() {
        return voice;
    }

    /**
     * Sets voice
     * 
     * @param voice New value for voice.
     **/
    public void setVoice(String voice) {
        this.voice = voice;
    }

    /**
     * Gets poweroutput
     * 
     * @return Value for poweroutput.
     **/
    public String getPoweroutput() {
        return poweroutput;
    }

    /**
     * Sets poweroutput
     * 
     * @param poweroutput New value for poweroutput.
     **/
    public void setPoweroutput(String poweroutput) {
        this.poweroutput = poweroutput;
    }

    /**
     * Gets voiceident
     * 
     * @return Value for voiceident.
     **/
    public String getVoiceident() {
        return voiceident;
    }

    /**
     * Sets voiceident
     * 
     * @param voiceident New value for voiceident.
     **/
    public void setVoiceident(String voiceident) {
        this.voiceident = voiceident;
    }

    /**
     * Gets monitoringcategory
     * 
     * @return Value for monitoringcategory.
     **/
    public String getMonitoringcategory() {
        return monitoringcategory;
    }

    /**
     * Sets monitoringcategory
     * 
     * @param monitoringcategory New value for monitoringcategory.
     **/
    public void setMonitoringcategory(String monitoringcategory) {
        this.monitoringcategory = monitoringcategory;
    }

    /**
     * Gets radiocallname
     * 
     * @return Value for radiocallname.
     **/
    public String getRadiocallname() {
        return radiocallname;
    }

    /**
     * Sets radiocallname
     * 
     * @param radiocallname New value for radiocallname.
     **/
    public void setRadiocallname(String radiocallname) {
        this.radiocallname = radiocallname;
    }

    /**
     * Gets tacanchannel
     * 
     * @return Value for tacanchannel.
     **/
    public String getTacanchannel() {
        return tacanchannel;
    }

    /**
     * Sets tacanchannel
     * 
     * @param tacanchannel New value for tacanchannel.
     **/
    public void setTacanchannel(String tacanchannel) {
        this.tacanchannel = tacanchannel;
    }

    /**
     * Gets frequency
     * 
     * @return Value for frequency.
     **/
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets frequency
     * 
     * @param frequency New value for frequency.
     **/
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    /**
     * Gets morsecodeident
     * 
     * @return Value for morsecodeident.
     **/
    public String getMorsecodeident() {
        return morsecodeident;
    }

    /**
     * Sets morsecodeident
     * 
     * @param morsecodeident New value for morsecodeident.
     **/
    public void setMorsecodeident(String morsecodeident) {
        this.morsecodeident = morsecodeident;
    }

    /**
     * Gets fanmarkertype
     * 
     * @return Value for fanmarkertype.
     **/
    public String getFanmarkertype() {
        return fanmarkertype;
    }

    /**
     * Sets fanmarkertype
     * 
     * @param fanmarkertype New value for fanmarkertype.
     **/
    public void setFanmarkertype(String fanmarkertype) {
        this.fanmarkertype = fanmarkertype;
    }

    /**
     * Gets truebearing
     * 
     * @return Value for truebearing.
     **/
    public String getTruebearing() {
        return truebearing;
    }

    /**
     * Sets truebearing
     * 
     * @param truebearing New value for truebearing.
     **/
    public void setTruebearing(String truebearing) {
        this.truebearing = truebearing;
    }

    /**
     * Gets protectedfreqaltitude
     * 
     * @return Value for protectedfreqaltitude.
     **/
    public String getProtectedfreqaltitude() {
        return protectedfreqaltitude;
    }

    /**
     * Sets protectedfreqaltitude
     * 
     * @param protectedfreqaltitude New value for protectedfreqaltitude.
     **/
    public void setProtectedfreqaltitude(String protectedfreqaltitude) {
        this.protectedfreqaltitude = protectedfreqaltitude;
    }

    /**
     * Gets highalthaslowradio
     * 
     * @return Value for highalthaslowradio.
     **/
    public String getHighalthaslowradio() {
        return highalthaslowradio;
    }

    /**
     * Sets highalthaslowradio
     * 
     * @param highalthaslowradio New value for highalthaslowradio.
     **/
    public void setHighalthaslowradio(String highalthaslowradio) {
        this.highalthaslowradio = highalthaslowradio;
    }

    /**
     * Gets navaidzmarker
     * 
     * @return Value for navaidzmarker.
     **/
    public String getNavaidzmarker() {
        return navaidzmarker;
    }

    /**
     * Sets navaidzmarker
     * 
     * @param navaidzmarker New value for navaidzmarker.
     **/
    public void setNavaidzmarker(String navaidzmarker) {
        this.navaidzmarker = navaidzmarker;
    }

    /**
     * Gets weatherbroadcasthours
     * 
     * @return Value for weatherbroadcasthours.
     **/
    public String getWeatherbroadcasthours() {
        return weatherbroadcasthours;
    }

    /**
     * Sets weatherbroadcasthours
     * 
     * @param weatherbroadcasthours New value for weatherbroadcasthours.
     **/
    public void setWeatherbroadcasthours(String weatherbroadcasthours) {
        this.weatherbroadcasthours = weatherbroadcasthours;
    }

    /**
     * Gets weatherbroadcastphone
     * 
     * @return Value for weatherbroadcastphone.
     **/
    public String getWeatherbroadcastphone() {
        return weatherbroadcastphone;
    }

    /**
     * Sets weatherbroadcastphone
     * 
     * @param weatherbroadcastphone New value for weatherbroadcastphone.
     **/
    public void setWeatherbroadcastphone(String weatherbroadcastphone) {
        this.weatherbroadcastphone = weatherbroadcastphone;
    }

    /**
     * Gets controllingfssident
     * 
     * @return Value for controllingfssident.
     **/
    public String getControllingfssident() {
        return controllingfssident;
    }

    /**
     * Sets controllingfssident
     * 
     * @param controllingfssident New value for controllingfssident.
     **/
    public void setControllingfssident(String controllingfssident) {
        this.controllingfssident = controllingfssident;
    }

    /**
     * Gets controllingfssname
     * 
     * @return Value for controllingfssname.
     **/
    public String getControllingfssname() {
        return controllingfssname;
    }

    /**
     * Sets controllingfssname
     * 
     * @param controllingfssname New value for controllingfssname.
     **/
    public void setControllingfssname(String controllingfssname) {
        this.controllingfssname = controllingfssname;
    }

    /**
     * Gets fsshours
     * 
     * @return Value for fsshours.
     **/
    public String getFsshours() {
        return fsshours;
    }

    /**
     * Sets fsshours
     * 
     * @param fsshours New value for fsshours.
     **/
    public void setFsshours(String fsshours) {
        this.fsshours = fsshours;
    }

    /**
     * Gets notamaccountabilitycode
     * 
     * @return Value for notamaccountabilitycode.
     **/
    public String getNotamaccountabilitycode() {
        return notamaccountabilitycode;
    }

    /**
     * Sets notamaccountabilitycode
     * 
     * @param notamaccountabilitycode New value for notamaccountabilitycode.
     **/
    public void setNotamaccountabilitycode(String notamaccountabilitycode) {
        this.notamaccountabilitycode = notamaccountabilitycode;
    }

    /**
     * Gets quadidentandrangelegbearing
     * 
     * @return Value for quadidentandrangelegbearing.
     **/
    public String getQuadidentandrangelegbearing() {
        return quadidentandrangelegbearing;
    }

    /**
     * Sets quadidentandrangelegbearing
     * 
     * @param quadidentandrangelegbearing New value for quadidentandrangelegbearing.
     **/
    public void setQuadidentandrangelegbearing(String quadidentandrangelegbearing) {
        this.quadidentandrangelegbearing = quadidentandrangelegbearing;
    }

    /**
     * Gets status
     * 
     * @return Value for status.
     **/
    public String getStatus() {
        return status;
    }

    /**
     * Sets status
     * 
     * @param status New value for status.
     **/
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Gets pitch
     * 
     * @return Value for pitch.
     **/
    public String getPitch() {
        return pitch;
    }

    /**
     * Sets pitch
     * 
     * @param pitch New value for pitch.
     **/
    public void setPitch(String pitch) {
        this.pitch = pitch;
    }

    /**
     * Gets fieldCatch
     * 
     * @return Value for fieldCatch.
     **/
    public String getFieldCatch() {
        return fieldCatch;
    }

    /**
     * Sets fieldCatch
     * 
     * @param fieldCatch New value for fieldCatch.
     **/
    public void setFieldCatch(String fieldCatch) {
        this.fieldCatch = fieldCatch;
    }

    /**
     * Gets suaatcaa
     * 
     * @return Value for suaatcaa.
     **/
    public String getSuaatcaa() {
        return suaatcaa;
    }

    /**
     * Sets suaatcaa
     * 
     * @param suaatcaa New value for suaatcaa.
     **/
    public void setSuaatcaa(String suaatcaa) {
        this.suaatcaa = suaatcaa;
    }

    /**
     * Gets restriction
     * 
     * @return Value for restriction.
     **/
    public String getRestriction() {
        return restriction;
    }

    /**
     * Sets restriction
     * 
     * @param restriction New value for restriction.
     **/
    public void setRestriction(String restriction) {
        this.restriction = restriction;
    }

    /**
     * Gets hiwas
     * 
     * @return Value for hiwas.
     **/
    public String getHiwas() {
        return hiwas;
    }

    /**
     * Sets hiwas
     * 
     * @param hiwas New value for hiwas.
     **/
    public void setHiwas(String hiwas) {
        this.hiwas = hiwas;
    }

    /**
     * Gets twebrestriction
     * 
     * @return Value for twebrestriction.
     **/
    public String getTwebrestriction() {
        return twebrestriction;
    }

    /**
     * Sets twebrestriction
     * 
     * @param twebrestriction New value for twebrestriction.
     **/
    public void setTwebrestriction(String twebrestriction) {
        this.twebrestriction = twebrestriction;
    }

    /**
     * Gets longituded
     * 
     * @return Value for longituded.
     **/
    public BigDecimal getLongituded() {
        return longituded;
    }

    /**
     * Sets longituded
     * 
     * @param longituded New value for longituded.
     **/
    public void setLongituded(BigDecimal longituded) {
        this.longituded = longituded;
    }

    /**
     * Gets latituded
     * 
     * @return Value for latituded.
     **/
    public BigDecimal getLatituded() {
        return latituded;
    }

    /**
     * Sets latituded
     * 
     * @param latituded New value for latituded.
     **/
    public void setLatituded(BigDecimal latituded) {
        this.latituded = latituded;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Navaid))
            return false;
        
        Navaid that = (Navaid)o;

        if (recordtype != null ? !recordtype.equals(that.recordtype) : that.recordtype != null)
            return false;
        

        if (facilityident != null ? !facilityident.equals(that.facilityident) : that.facilityident != null)
            return false;
        

        if (facilitytype != null ? !facilitytype.equals(that.facilitytype) : that.facilitytype != null)
            return false;
        

        if (navaidident != null ? !navaidident.equals(that.navaidident) : that.navaidident != null)
            return false;
        

        if (effectivedate != null ? !effectivedate.equals(that.effectivedate) : that.effectivedate != null)
            return false;
        

        if (navaidname != null ? !navaidname.equals(that.navaidname) : that.navaidname != null)
            return false;
        

        if (city != null ? !city.equals(that.city) : that.city != null)
            return false;
        

        if (state != null ? !state.equals(that.state) : that.state != null)
            return false;
        

        if (stateabbr != null ? !stateabbr.equals(that.stateabbr) : that.stateabbr != null)
            return false;
        

        if (faaregion != null ? !faaregion.equals(that.faaregion) : that.faaregion != null)
            return false;
        

        if (country != null ? !country.equals(that.country) : that.country != null)
            return false;
        

        if (countryabbr != null ? !countryabbr.equals(that.countryabbr) : that.countryabbr != null)
            return false;
        

        if (ownername != null ? !ownername.equals(that.ownername) : that.ownername != null)
            return false;
        

        if (operatorname != null ? !operatorname.equals(that.operatorname) : that.operatorname != null)
            return false;
        

        if (commonusage != null ? !commonusage.equals(that.commonusage) : that.commonusage != null)
            return false;
        

        if (publicuse != null ? !publicuse.equals(that.publicuse) : that.publicuse != null)
            return false;
        

        if (operationalhours != null ? !operationalhours.equals(that.operationalhours) : that.operationalhours != null)
            return false;
        

        if (identhigh != null ? !identhigh.equals(that.identhigh) : that.identhigh != null)
            return false;
        

        if (artcchigh != null ? !artcchigh.equals(that.artcchigh) : that.artcchigh != null)
            return false;
        

        if (identlow != null ? !identlow.equals(that.identlow) : that.identlow != null)
            return false;
        

        if (artcclow != null ? !artcclow.equals(that.artcclow) : that.artcclow != null)
            return false;
        

        if (latitude != null ? !latitude.equals(that.latitude) : that.latitude != null)
            return false;
        

        if (latitudes != null ? !latitudes.equals(that.latitudes) : that.latitudes != null)
            return false;
        

        if (longitude != null ? !longitude.equals(that.longitude) : that.longitude != null)
            return false;
        

        if (longitudes != null ? !longitudes.equals(that.longitudes) : that.longitudes != null)
            return false;
        

        if (latlongaccuracy != null ? !latlongaccuracy.equals(that.latlongaccuracy) : that.latlongaccuracy != null)
            return false;
        

        if (tacanlatitude != null ? !tacanlatitude.equals(that.tacanlatitude) : that.tacanlatitude != null)
            return false;
        

        if (tacanlatitudes != null ? !tacanlatitudes.equals(that.tacanlatitudes) : that.tacanlatitudes != null)
            return false;
        

        if (tacanlongitude != null ? !tacanlongitude.equals(that.tacanlongitude) : that.tacanlongitude != null)
            return false;
        

        if (tacanlongitudes != null ? !tacanlongitudes.equals(that.tacanlongitudes) : that.tacanlongitudes != null)
            return false;
        

        if (elevation != null ? !elevation.equals(that.elevation) : that.elevation != null)
            return false;
        

        if (magneticvariation != null ? !magneticvariation.equals(that.magneticvariation) : that.magneticvariation != null)
            return false;
        

        if (magneticvariationepoch != null ? !magneticvariationepoch.equals(that.magneticvariationepoch) : that.magneticvariationepoch != null)
            return false;
        

        if (voice != null ? !voice.equals(that.voice) : that.voice != null)
            return false;
        

        if (poweroutput != null ? !poweroutput.equals(that.poweroutput) : that.poweroutput != null)
            return false;
        

        if (voiceident != null ? !voiceident.equals(that.voiceident) : that.voiceident != null)
            return false;
        

        if (monitoringcategory != null ? !monitoringcategory.equals(that.monitoringcategory) : that.monitoringcategory != null)
            return false;
        

        if (radiocallname != null ? !radiocallname.equals(that.radiocallname) : that.radiocallname != null)
            return false;
        

        if (tacanchannel != null ? !tacanchannel.equals(that.tacanchannel) : that.tacanchannel != null)
            return false;
        

        if (frequency != null ? !frequency.equals(that.frequency) : that.frequency != null)
            return false;
        

        if (morsecodeident != null ? !morsecodeident.equals(that.morsecodeident) : that.morsecodeident != null)
            return false;
        

        if (fanmarkertype != null ? !fanmarkertype.equals(that.fanmarkertype) : that.fanmarkertype != null)
            return false;
        

        if (truebearing != null ? !truebearing.equals(that.truebearing) : that.truebearing != null)
            return false;
        

        if (protectedfreqaltitude != null ? !protectedfreqaltitude.equals(that.protectedfreqaltitude) : that.protectedfreqaltitude != null)
            return false;
        

        if (highalthaslowradio != null ? !highalthaslowradio.equals(that.highalthaslowradio) : that.highalthaslowradio != null)
            return false;
        

        if (navaidzmarker != null ? !navaidzmarker.equals(that.navaidzmarker) : that.navaidzmarker != null)
            return false;
        

        if (weatherbroadcasthours != null ? !weatherbroadcasthours.equals(that.weatherbroadcasthours) : that.weatherbroadcasthours != null)
            return false;
        

        if (weatherbroadcastphone != null ? !weatherbroadcastphone.equals(that.weatherbroadcastphone) : that.weatherbroadcastphone != null)
            return false;
        

        if (controllingfssident != null ? !controllingfssident.equals(that.controllingfssident) : that.controllingfssident != null)
            return false;
        

        if (controllingfssname != null ? !controllingfssname.equals(that.controllingfssname) : that.controllingfssname != null)
            return false;
        

        if (fsshours != null ? !fsshours.equals(that.fsshours) : that.fsshours != null)
            return false;
        

        if (notamaccountabilitycode != null ? !notamaccountabilitycode.equals(that.notamaccountabilitycode) : that.notamaccountabilitycode != null)
            return false;
        

        if (quadidentandrangelegbearing != null ? !quadidentandrangelegbearing.equals(that.quadidentandrangelegbearing) : that.quadidentandrangelegbearing != null)
            return false;
        

        if (status != null ? !status.equals(that.status) : that.status != null)
            return false;
        

        if (pitch != null ? !pitch.equals(that.pitch) : that.pitch != null)
            return false;
        

        if (fieldCatch != null ? !fieldCatch.equals(that.fieldCatch) : that.fieldCatch != null)
            return false;
        

        if (suaatcaa != null ? !suaatcaa.equals(that.suaatcaa) : that.suaatcaa != null)
            return false;
        

        if (restriction != null ? !restriction.equals(that.restriction) : that.restriction != null)
            return false;
        

        if (hiwas != null ? !hiwas.equals(that.hiwas) : that.hiwas != null)
            return false;
        

        if (twebrestriction != null ? !twebrestriction.equals(that.twebrestriction) : that.twebrestriction != null)
            return false;
        

        if (longituded != null ? !longituded.equals(that.longituded) : that.longituded != null)
            return false;
        

        if (latituded != null ? !latituded.equals(that.latituded) : that.latituded != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = recordtype != null ? recordtype.hashCode() : 0;

        res = 31 * res + (facilityident != null ? facilityident.hashCode() : 0);

        res = 31 * res + (facilitytype != null ? facilitytype.hashCode() : 0);

        res = 31 * res + (navaidident != null ? navaidident.hashCode() : 0);

        res = 31 * res + (effectivedate != null ? effectivedate.hashCode() : 0);

        res = 31 * res + (navaidname != null ? navaidname.hashCode() : 0);

        res = 31 * res + (city != null ? city.hashCode() : 0);

        res = 31 * res + (state != null ? state.hashCode() : 0);

        res = 31 * res + (stateabbr != null ? stateabbr.hashCode() : 0);

        res = 31 * res + (faaregion != null ? faaregion.hashCode() : 0);

        res = 31 * res + (country != null ? country.hashCode() : 0);

        res = 31 * res + (countryabbr != null ? countryabbr.hashCode() : 0);

        res = 31 * res + (ownername != null ? ownername.hashCode() : 0);

        res = 31 * res + (operatorname != null ? operatorname.hashCode() : 0);

        res = 31 * res + (commonusage != null ? commonusage.hashCode() : 0);

        res = 31 * res + (publicuse != null ? publicuse.hashCode() : 0);

        res = 31 * res + (operationalhours != null ? operationalhours.hashCode() : 0);

        res = 31 * res + (identhigh != null ? identhigh.hashCode() : 0);

        res = 31 * res + (artcchigh != null ? artcchigh.hashCode() : 0);

        res = 31 * res + (identlow != null ? identlow.hashCode() : 0);

        res = 31 * res + (artcclow != null ? artcclow.hashCode() : 0);

        res = 31 * res + (latitude != null ? latitude.hashCode() : 0);

        res = 31 * res + (latitudes != null ? latitudes.hashCode() : 0);

        res = 31 * res + (longitude != null ? longitude.hashCode() : 0);

        res = 31 * res + (longitudes != null ? longitudes.hashCode() : 0);

        res = 31 * res + (latlongaccuracy != null ? latlongaccuracy.hashCode() : 0);

        res = 31 * res + (tacanlatitude != null ? tacanlatitude.hashCode() : 0);

        res = 31 * res + (tacanlatitudes != null ? tacanlatitudes.hashCode() : 0);

        res = 31 * res + (tacanlongitude != null ? tacanlongitude.hashCode() : 0);

        res = 31 * res + (tacanlongitudes != null ? tacanlongitudes.hashCode() : 0);

        res = 31 * res + (elevation != null ? elevation.hashCode() : 0);

        res = 31 * res + (magneticvariation != null ? magneticvariation.hashCode() : 0);

        res = 31 * res + (magneticvariationepoch != null ? magneticvariationepoch.hashCode() : 0);

        res = 31 * res + (voice != null ? voice.hashCode() : 0);

        res = 31 * res + (poweroutput != null ? poweroutput.hashCode() : 0);

        res = 31 * res + (voiceident != null ? voiceident.hashCode() : 0);

        res = 31 * res + (monitoringcategory != null ? monitoringcategory.hashCode() : 0);

        res = 31 * res + (radiocallname != null ? radiocallname.hashCode() : 0);

        res = 31 * res + (tacanchannel != null ? tacanchannel.hashCode() : 0);

        res = 31 * res + (frequency != null ? frequency.hashCode() : 0);

        res = 31 * res + (morsecodeident != null ? morsecodeident.hashCode() : 0);

        res = 31 * res + (fanmarkertype != null ? fanmarkertype.hashCode() : 0);

        res = 31 * res + (truebearing != null ? truebearing.hashCode() : 0);

        res = 31 * res + (protectedfreqaltitude != null ? protectedfreqaltitude.hashCode() : 0);

        res = 31 * res + (highalthaslowradio != null ? highalthaslowradio.hashCode() : 0);

        res = 31 * res + (navaidzmarker != null ? navaidzmarker.hashCode() : 0);

        res = 31 * res + (weatherbroadcasthours != null ? weatherbroadcasthours.hashCode() : 0);

        res = 31 * res + (weatherbroadcastphone != null ? weatherbroadcastphone.hashCode() : 0);

        res = 31 * res + (controllingfssident != null ? controllingfssident.hashCode() : 0);

        res = 31 * res + (controllingfssname != null ? controllingfssname.hashCode() : 0);

        res = 31 * res + (fsshours != null ? fsshours.hashCode() : 0);

        res = 31 * res + (notamaccountabilitycode != null ? notamaccountabilitycode.hashCode() : 0);

        res = 31 * res + (quadidentandrangelegbearing != null ? quadidentandrangelegbearing.hashCode() : 0);

        res = 31 * res + (status != null ? status.hashCode() : 0);

        res = 31 * res + (pitch != null ? pitch.hashCode() : 0);

        res = 31 * res + (fieldCatch != null ? fieldCatch.hashCode() : 0);

        res = 31 * res + (suaatcaa != null ? suaatcaa.hashCode() : 0);

        res = 31 * res + (restriction != null ? restriction.hashCode() : 0);

        res = 31 * res + (hiwas != null ? hiwas.hashCode() : 0);

        res = 31 * res + (twebrestriction != null ? twebrestriction.hashCode() : 0);

        res = 31 * res + (longituded != null ? longituded.hashCode() : 0);

        res = 31 * res + (latituded != null ? latituded.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Navaid [" + 
            "recordtype=" + recordtype + ", " + 
            "facilityident=" + facilityident + ", " + 
            "facilitytype=" + facilitytype + ", " + 
            "navaidident=" + navaidident + ", " + 
            "effectivedate=" + effectivedate + ", " + 
            "navaidname=" + navaidname + ", " + 
            "city=" + city + ", " + 
            "state=" + state + ", " + 
            "stateabbr=" + stateabbr + ", " + 
            "faaregion=" + faaregion + ", " + 
            "country=" + country + ", " + 
            "countryabbr=" + countryabbr + ", " + 
            "ownername=" + ownername + ", " + 
            "operatorname=" + operatorname + ", " + 
            "commonusage=" + commonusage + ", " + 
            "publicuse=" + publicuse + ", " + 
            "operationalhours=" + operationalhours + ", " + 
            "identhigh=" + identhigh + ", " + 
            "artcchigh=" + artcchigh + ", " + 
            "identlow=" + identlow + ", " + 
            "artcclow=" + artcclow + ", " + 
            "latitude=" + latitude + ", " + 
            "latitudes=" + latitudes + ", " + 
            "longitude=" + longitude + ", " + 
            "longitudes=" + longitudes + ", " + 
            "latlongaccuracy=" + latlongaccuracy + ", " + 
            "tacanlatitude=" + tacanlatitude + ", " + 
            "tacanlatitudes=" + tacanlatitudes + ", " + 
            "tacanlongitude=" + tacanlongitude + ", " + 
            "tacanlongitudes=" + tacanlongitudes + ", " + 
            "elevation=" + elevation + ", " + 
            "magneticvariation=" + magneticvariation + ", " + 
            "magneticvariationepoch=" + magneticvariationepoch + ", " + 
            "voice=" + voice + ", " + 
            "poweroutput=" + poweroutput + ", " + 
            "voiceident=" + voiceident + ", " + 
            "monitoringcategory=" + monitoringcategory + ", " + 
            "radiocallname=" + radiocallname + ", " + 
            "tacanchannel=" + tacanchannel + ", " + 
            "frequency=" + frequency + ", " + 
            "morsecodeident=" + morsecodeident + ", " + 
            "fanmarkertype=" + fanmarkertype + ", " + 
            "truebearing=" + truebearing + ", " + 
            "protectedfreqaltitude=" + protectedfreqaltitude + ", " + 
            "highalthaslowradio=" + highalthaslowradio + ", " + 
            "navaidzmarker=" + navaidzmarker + ", " + 
            "weatherbroadcasthours=" + weatherbroadcasthours + ", " + 
            "weatherbroadcastphone=" + weatherbroadcastphone + ", " + 
            "controllingfssident=" + controllingfssident + ", " + 
            "controllingfssname=" + controllingfssname + ", " + 
            "fsshours=" + fsshours + ", " + 
            "notamaccountabilitycode=" + notamaccountabilitycode + ", " + 
            "quadidentandrangelegbearing=" + quadidentandrangelegbearing + ", " + 
            "status=" + status + ", " + 
            "pitch=" + pitch + ", " + 
            "fieldCatch=" + fieldCatch + ", " + 
            "suaatcaa=" + suaatcaa + ", " + 
            "restriction=" + restriction + ", " + 
            "hiwas=" + hiwas + ", " + 
            "twebrestriction=" + twebrestriction + ", " + 
            "longituded=" + longituded + ", " + 
            "latituded=" + latituded +
        "]";
    }
}