package com.pluralsight.duckair.model;

import java.io.Serializable;

/**
 * RouteMetadata definition.
 * 
 * This file was generated by Ignite Web Console (03/21/2019, 13:45)
 **/
public class RouteMetadata implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for routeId. */
    private String routeId;

    /** Value for fromIcao. */
    private String fromIcao;

    /** Value for toIcao. */
    private String toIcao;

    /** Value for fromName. */
    private String fromName;

    /** Value for toName. */
    private String toName;

    /** Value for distance. */
    private Integer distance;

    /** Value for waypoints. */
    private int waypoints;

    /** Empty constructor. **/
    public RouteMetadata() {
        // No-op.
    }

    /** Full constructor. **/
    public RouteMetadata(String routeId,
        String fromIcao,
        String toIcao,
        String fromName,
        String toName,
        Integer distance,
        int waypoints) {
        this.routeId = routeId;
        this.fromIcao = fromIcao;
        this.toIcao = toIcao;
        this.fromName = fromName;
        this.toName = toName;
        this.distance = distance;
        this.waypoints = waypoints;
    }

    /**
     * Gets routeId
     * 
     * @return Value for routeId.
     **/
    public String getRouteId() {
        return routeId;
    }

    /**
     * Sets routeId
     * 
     * @param routeId New value for routeId.
     **/
    public void setRouteId(String routeId) {
        this.routeId = routeId;
    }

    /**
     * Gets fromIcao
     * 
     * @return Value for fromIcao.
     **/
    public String getFromIcao() {
        return fromIcao;
    }

    /**
     * Sets fromIcao
     * 
     * @param fromIcao New value for fromIcao.
     **/
    public void setFromIcao(String fromIcao) {
        this.fromIcao = fromIcao;
    }

    /**
     * Gets toIcao
     * 
     * @return Value for toIcao.
     **/
    public String getToIcao() {
        return toIcao;
    }

    /**
     * Sets toIcao
     * 
     * @param toIcao New value for toIcao.
     **/
    public void setToIcao(String toIcao) {
        this.toIcao = toIcao;
    }

    /**
     * Gets fromName
     * 
     * @return Value for fromName.
     **/
    public String getFromName() {
        return fromName;
    }

    /**
     * Sets fromName
     * 
     * @param fromName New value for fromName.
     **/
    public void setFromName(String fromName) {
        this.fromName = fromName;
    }

    /**
     * Gets toName
     * 
     * @return Value for toName.
     **/
    public String getToName() {
        return toName;
    }

    /**
     * Sets toName
     * 
     * @param toName New value for toName.
     **/
    public void setToName(String toName) {
        this.toName = toName;
    }

    /**
     * Gets distance
     * 
     * @return Value for distance.
     **/
    public Integer getDistance() {
        return distance;
    }

    /**
     * Sets distance
     * 
     * @param distance New value for distance.
     **/
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * Gets waypoints
     * 
     * @return Value for waypoints.
     **/
    public int getWaypoints() {
        return waypoints;
    }

    /**
     * Sets waypoints
     * 
     * @param waypoints New value for waypoints.
     **/
    public void setWaypoints(int waypoints) {
        this.waypoints = waypoints;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof RouteMetadata))
            return false;
        
        RouteMetadata that = (RouteMetadata)o;

        if (routeId != null ? !routeId.equals(that.routeId) : that.routeId != null)
            return false;
        

        if (fromIcao != null ? !fromIcao.equals(that.fromIcao) : that.fromIcao != null)
            return false;
        

        if (toIcao != null ? !toIcao.equals(that.toIcao) : that.toIcao != null)
            return false;
        

        if (fromName != null ? !fromName.equals(that.fromName) : that.fromName != null)
            return false;
        

        if (toName != null ? !toName.equals(that.toName) : that.toName != null)
            return false;
        

        if (distance != null ? !distance.equals(that.distance) : that.distance != null)
            return false;
        

        if (waypoints != that.waypoints)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = routeId != null ? routeId.hashCode() : 0;

        res = 31 * res + (fromIcao != null ? fromIcao.hashCode() : 0);

        res = 31 * res + (toIcao != null ? toIcao.hashCode() : 0);

        res = 31 * res + (fromName != null ? fromName.hashCode() : 0);

        res = 31 * res + (toName != null ? toName.hashCode() : 0);

        res = 31 * res + (distance != null ? distance.hashCode() : 0);

        res = 31 * res + (waypoints);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "RouteMetadata [" + 
            "routeId=" + routeId + ", " + 
            "fromIcao=" + fromIcao + ", " + 
            "toIcao=" + toIcao + ", " + 
            "fromName=" + fromName + ", " + 
            "toName=" + toName + ", " + 
            "distance=" + distance + ", " + 
            "waypoints=" + waypoints +
        "]";
    }
}