package load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (03/21/2019, 13:45) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start("DuckAirlines-client.xml")) {
            System.out.println(">>> Loading caches...");

            System.out.println(">>> Loading cache: AircraftCache");
            ignite.cache("AircraftCache").loadCache(null);

            System.out.println(">>> Loading cache: AirportsCache");
            ignite.cache("AirportsCache").loadCache(null);

            System.out.println(">>> Loading cache: CrewCache");
            ignite.cache("CrewCache").loadCache(null);

            System.out.println(">>> Loading cache: CustomersCache");
            ignite.cache("CustomersCache").loadCache(null);

            System.out.println(">>> Loading cache: FixCache");
            ignite.cache("FixCache").loadCache(null);

            System.out.println(">>> Loading cache: FleetCache");
            ignite.cache("FleetCache").loadCache(null);

            System.out.println(">>> Loading cache: FlightPlansCache");
            ignite.cache("FlightPlansCache").loadCache(null);

            System.out.println(">>> Loading cache: FlightsCache");
            ignite.cache("FlightsCache").loadCache(null);

            System.out.println(">>> Loading cache: FrequentFlyerCache");
            ignite.cache("FrequentFlyerCache").loadCache(null);

            System.out.println(">>> Loading cache: NavaidCache");
            ignite.cache("NavaidCache").loadCache(null);

            System.out.println(">>> Loading cache: PilotLogsCache");
            ignite.cache("PilotLogsCache").loadCache(null);

            System.out.println(">>> Loading cache: RouteMetadataCache");
            ignite.cache("RouteMetadataCache").loadCache(null);

            System.out.println(">>> Loading cache: RouteSegmentsCache");
            ignite.cache("RouteSegmentsCache").loadCache(null);

            System.out.println(">>> Loading cache: RunwayCache");
            ignite.cache("RunwayCache").loadCache(null);

            System.out.println(">>> Loading cache: TelemetryCache");
            ignite.cache("TelemetryCache").loadCache(null);

            System.out.println(">>> Loading cache: WindsCache");
            ignite.cache("WindsCache").loadCache(null);

            System.out.println(">>> All caches loaded!");
        }
    }
}